In [ ]:
import pandas as pd

df = pd.read_csv("/content/Final Primary_dataset_from_Indonesian_Private_University.csv")

In [ ]:
display(df)

,age,Gender,Work tenure,Education,Job position,Unnamed: 5,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,...,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,26-35 year,Male,3 - 5 years,Master's degree,Senior lecturer,NaN,less than 40,4,3,3,...,3,5.001.000IDR-10.000.000 IDR,3,3,3,3,3,3,3,1
1,26-35 year,Female,Less than 2 years,Bachelor's degree,Lecturer,NaN,less than 40,3,4,4,...,4,3.000.000 IDR -5.000.000 IDR,4,4,4,3,2,2,2,0
2,46-55 year,Female,more than 5 years,Doctorate or other advanced degree,Professor,NaN,40-45,3,4,4,...,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,4,4,4,4,4,4,1
3,more than 56 year,Female,more than 5 years,Doctorate or other advanced degree,Professor,NaN,51-55,3,4,4,...,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,5,5,4,1,1,2,0
4,26-35 year,Female,3 - 5 years,Bachelor's degree,Lecturer,NaN,40-45,3,2,5,...,4,3.000.000 IDR -5.000.000 IDR,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,18-25 year,Male,Less than 2 years,Masters,Lecturer,NaN,less than 40,5,5,5,...,5,3.000.000 IDR -5.000.000 IDR,5,5,4,5,2,2,2,0
522,36-45 year,Male,3 - 5 years,Bachelor's degree,Lecturer,NaN,51-55,2,2,3,...,2,3.000.000 IDR -5.000.000 IDR,2,3,2,1,5,5,5,1
523,36-45 year,Female,more than 5 years,Master's degree,Lecturer,NaN,51-55,4,2,5,...,4,5.001.000IDR-10.000.000 IDR,3,4,5,5,2,2,4,0
524,more than 56 year,Female,more than 5 years,Master's degree,Senior lecturer,NaN,40-45,4,4,4,...,4,3.000.000 IDR -5.000.000 IDR,4,5,5,4,1,1,2,0
525,more than 56 year,Male,more than 5 years,Master's degree,Lecturer,NaN,less than 40,4,4,4,...,4,10.000.000 IDR-20.000.000 IDR,4,4,4,4,1,2,2,0

In [ ]:
del df["Unnamed: 5"]

In [ ]:
display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,26-35 year,Male,3 - 5 years,Master's degree,Senior lecturer,less than 40,4,3,3,3,3,5.001.000IDR-10.000.000 IDR,3,3,3,3,3,3,3,1
1,26-35 year,Female,Less than 2 years,Bachelor's degree,Lecturer,less than 40,3,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,4,4,3,2,2,2,0
2,46-55 year,Female,more than 5 years,Doctorate or other advanced degree,Professor,40-45,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,4,4,4,4,4,4,1
3,more than 56 year,Female,more than 5 years,Doctorate or other advanced degree,Professor,51-55,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,5,5,4,1,1,2,0
4,26-35 year,Female,3 - 5 years,Bachelor's degree,Lecturer,40-45,3,2,5,3,4,3.000.000 IDR -5.000.000 IDR,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,18-25 year,Male,Less than 2 years,Masters,Lecturer,less than 40,5,5,5,5,5,3.000.000 IDR -5.000.000 IDR,5,5,4,5,2,2,2,0
522,36-45 year,Male,3 - 5 years,Bachelor's degree,Lecturer,51-55,2,2,3,2,2,3.000.000 IDR -5.000.000 IDR,2,3,2,1,5,5,5,1
523,36-45 year,Female,more than 5 years,Master's degree,Lecturer,51-55,4,2,5,4,4,5.001.000IDR-10.000.000 IDR,3,4,5,5,2,2,4,0
524,more than 56 year,Female,more than 5 years,Master's degree,Senior lecturer,40-45,4,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,5,5,4,1,1,2,0
525,more than 56 year,Male,more than 5 years,Master's degree,Lecturer,less than 40,4,4,4,4,4,10.000.000 IDR-20.000.000 IDR,4,4,4,4,1,2,2,0

In [ ]:
# import pandas as pd
# import scipy.stats as stats

# # Load dataset
# file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'
# df = pd.read_csv(file_path)

# # Clean column names (strip spaces)
# df.columns = df.columns.str.strip()

# # Features and target
# features = [
#     'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
#     'satisfaction with workload', 'satisfied  compensation ',
#     'good relationship with peers', 'satisfied with career and  opportunity',
#     'satisfied with job profession ', 'monthly salary',
#     'satisfied with  work-life balance', 'work is meaningful',
#     'family support', 'mentally well and do not have anxiety'
# ]
# target = 'TOI (turnover intention)'

# # Normalize feature names
# features = [f.strip() for f in features]
# target = target.strip()

# # Chi-Square calculation
# chi_results = []
# for col in features:
#     if col not in df.columns:
#         continue
#     contingency = pd.crosstab(df[col], df[target])
#     chi2, p, _, _ = stats.chi2_contingency(contingency)
#     chi_results.append([col, chi2, p])

# # Create results table
# chi_square_table = pd.DataFrame(
#     chi_results, columns=["Feature", "Chi2", "p-value"]
# ).sort_values(by="Chi2", ascending=False).reset_index(drop=True)

# # Show results
# print(chi_square_table)

In [ ]:
print(df['age'].unique())   # replace with your column name

['26-35 year' '46-55 year' 'more than 56 year' '36-45 year' '18-25 year']

In [ ]:
import pandas as pd

# Suppose your dataframe is df
age_order = {
    '18-25 year': 0,
    '26-35 year': 1,
    '36-45 year': 2,
    '46-55 year': 3,
    'more than 56 year': 4
}

df['age'] = df['age'].map(age_order)

In [ ]:
display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,1,Male,3 - 5 years,Master's degree,Senior lecturer,less than 40,4,3,3,3,3,5.001.000IDR-10.000.000 IDR,3,3,3,3,3,3,3,1
1,1,Female,Less than 2 years,Bachelor's degree,Lecturer,less than 40,3,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,4,4,3,2,2,2,0
2,3,Female,more than 5 years,Doctorate or other advanced degree,Professor,40-45,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,4,4,4,4,4,4,1
3,4,Female,more than 5 years,Doctorate or other advanced degree,Professor,51-55,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,5,5,4,1,1,2,0
4,1,Female,3 - 5 years,Bachelor's degree,Lecturer,40-45,3,2,5,3,4,3.000.000 IDR -5.000.000 IDR,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,Male,Less than 2 years,Masters,Lecturer,less than 40,5,5,5,5,5,3.000.000 IDR -5.000.000 IDR,5,5,4,5,2,2,2,0
522,2,Male,3 - 5 years,Bachelor's degree,Lecturer,51-55,2,2,3,2,2,3.000.000 IDR -5.000.000 IDR,2,3,2,1,5,5,5,1
523,2,Female,more than 5 years,Master's degree,Lecturer,51-55,4,2,5,4,4,5.001.000IDR-10.000.000 IDR,3,4,5,5,2,2,4,0
524,4,Female,more than 5 years,Master's degree,Senior lecturer,40-45,4,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,5,5,4,1,1,2,0
525,4,Male,more than 5 years,Master's degree,Lecturer,less than 40,4,4,4,4,4,10.000.000 IDR-20.000.000 IDR,4,4,4,4,1,2,2,0

In [ ]:
print(df['Gender'].unique())

['Male' 'Female']

In [ ]:
# Convert to string
df['Gender'] = df['Gender'].astype(str)



# Map to numeric
Gender_order = {
    'Male': 0,
    'Female': 1
}

df['Gender'] = df['Gender'].map(Gender_order)

In [ ]:

display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,1,0,3 - 5 years,Master's degree,Senior lecturer,less than 40,4,3,3,3,3,5.001.000IDR-10.000.000 IDR,3,3,3,3,3,3,3,1
1,1,1,Less than 2 years,Bachelor's degree,Lecturer,less than 40,3,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,4,4,3,2,2,2,0
2,3,1,more than 5 years,Doctorate or other advanced degree,Professor,40-45,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,4,4,4,4,4,4,1
3,4,1,more than 5 years,Doctorate or other advanced degree,Professor,51-55,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,5,5,4,1,1,2,0
4,1,1,3 - 5 years,Bachelor's degree,Lecturer,40-45,3,2,5,3,4,3.000.000 IDR -5.000.000 IDR,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,Less than 2 years,Masters,Lecturer,less than 40,5,5,5,5,5,3.000.000 IDR -5.000.000 IDR,5,5,4,5,2,2,2,0
522,2,0,3 - 5 years,Bachelor's degree,Lecturer,51-55,2,2,3,2,2,3.000.000 IDR -5.000.000 IDR,2,3,2,1,5,5,5,1
523,2,1,more than 5 years,Master's degree,Lecturer,51-55,4,2,5,4,4,5.001.000IDR-10.000.000 IDR,3,4,5,5,2,2,4,0
524,4,1,more than 5 years,Master's degree,Senior lecturer,40-45,4,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,5,5,4,1,1,2,0
525,4,0,more than 5 years,Master's degree,Lecturer,less than 40,4,4,4,4,4,10.000.000 IDR-20.000.000 IDR,4,4,4,4,1,2,2,0

In [ ]:
print(df['Work tenure'].unique())

['3 - 5 years' 'Less than 2 years' 'more than 5 years'
 'Less than 2 years ']

In [ ]:
df['Work tenure'] = df['Work tenure'].str.upper().str.strip()

In [ ]:
print(df['Work tenure'].unique())

['3 - 5 YEARS' 'LESS THAN 2 YEARS' 'MORE THAN 5 YEARS']

In [ ]:


# Define proper order mapping
tenure_order = {
    '3 - 5 YEARS':1,
     'LESS THAN 2 YEARS': 0,
     'MORE THAN 5 YEARS':2


}

# Apply mapping
df['Work tenure'] = df['Work tenure'].map(tenure_order)

# Convert to string
p = df['Work tenure'].astype(int)

In [ ]:
display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,1,0,1,Master's degree,Senior lecturer,less than 40,4,3,3,3,3,5.001.000IDR-10.000.000 IDR,3,3,3,3,3,3,3,1
1,1,1,0,Bachelor's degree,Lecturer,less than 40,3,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,4,4,3,2,2,2,0
2,3,1,2,Doctorate or other advanced degree,Professor,40-45,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,4,4,4,4,4,4,1
3,4,1,2,Doctorate or other advanced degree,Professor,51-55,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,5,5,4,1,1,2,0
4,1,1,1,Bachelor's degree,Lecturer,40-45,3,2,5,3,4,3.000.000 IDR -5.000.000 IDR,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,0,Masters,Lecturer,less than 40,5,5,5,5,5,3.000.000 IDR -5.000.000 IDR,5,5,4,5,2,2,2,0
522,2,0,1,Bachelor's degree,Lecturer,51-55,2,2,3,2,2,3.000.000 IDR -5.000.000 IDR,2,3,2,1,5,5,5,1
523,2,1,2,Master's degree,Lecturer,51-55,4,2,5,4,4,5.001.000IDR-10.000.000 IDR,3,4,5,5,2,2,4,0
524,4,1,2,Master's degree,Senior lecturer,40-45,4,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,5,5,4,1,1,2,0
525,4,0,2,Master's degree,Lecturer,less than 40,4,4,4,4,4,10.000.000 IDR-20.000.000 IDR,4,4,4,4,1,2,2,0

In [ ]:
print(df['Education'].unique())

["Master's degree" "Bachelor's degree "
 'Doctorate or other advanced degree' 'Masters' 'Masters '
 "Bachelor's degree" 'High School ' 'Masters degree']

In [ ]:


# Standardize similar values
df['Education'] = df['Education'].replace({
    "Masters": "Master's degree",
    "Masters ": "Master's degree",
    "Masters degree": "Master's degree",
    "Bachelor's degree ": "Bachelor's degree",
    "High School ": "High School"
})

# Define proper order mapping
education_order = {
    'High School': 0,
    "Bachelor's degree": 1,
    "Master's degree": 2,
    'Doctorate or other advanced degree': 3
}

# Apply mapping
df['Education'] = df['Education'].map(education_order)

In [ ]:


display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,1,0,1,2,Senior lecturer,less than 40,4,3,3,3,3,5.001.000IDR-10.000.000 IDR,3,3,3,3,3,3,3,1
1,1,1,0,1,Lecturer,less than 40,3,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,4,4,3,2,2,2,0
2,3,1,2,3,Professor,40-45,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,4,4,4,4,4,4,1
3,4,1,2,3,Professor,51-55,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,5,5,4,1,1,2,0
4,1,1,1,1,Lecturer,40-45,3,2,5,3,4,3.000.000 IDR -5.000.000 IDR,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,0,2,Lecturer,less than 40,5,5,5,5,5,3.000.000 IDR -5.000.000 IDR,5,5,4,5,2,2,2,0
522,2,0,1,1,Lecturer,51-55,2,2,3,2,2,3.000.000 IDR -5.000.000 IDR,2,3,2,1,5,5,5,1
523,2,1,2,2,Lecturer,51-55,4,2,5,4,4,5.001.000IDR-10.000.000 IDR,3,4,5,5,2,2,4,0
524,4,1,2,2,Senior lecturer,40-45,4,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,5,5,4,1,1,2,0
525,4,0,2,2,Lecturer,less than 40,4,4,4,4,4,10.000.000 IDR-20.000.000 IDR,4,4,4,4,1,2,2,0

In [ ]:
display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,1,0,1,2,Senior lecturer,less than 40,4,3,3,3,3,5.001.000IDR-10.000.000 IDR,3,3,3,3,3,3,3,1
1,1,1,0,1,Lecturer,less than 40,3,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,4,4,3,2,2,2,0
2,3,1,2,3,Professor,40-45,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,4,4,4,4,4,4,1
3,4,1,2,3,Professor,51-55,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,5,5,4,1,1,2,0
4,1,1,1,1,Lecturer,40-45,3,2,5,3,4,3.000.000 IDR -5.000.000 IDR,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,0,2,Lecturer,less than 40,5,5,5,5,5,3.000.000 IDR -5.000.000 IDR,5,5,4,5,2,2,2,0
522,2,0,1,1,Lecturer,51-55,2,2,3,2,2,3.000.000 IDR -5.000.000 IDR,2,3,2,1,5,5,5,1
523,2,1,2,2,Lecturer,51-55,4,2,5,4,4,5.001.000IDR-10.000.000 IDR,3,4,5,5,2,2,4,0
524,4,1,2,2,Senior lecturer,40-45,4,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,5,5,4,1,1,2,0
525,4,0,2,2,Lecturer,less than 40,4,4,4,4,4,10.000.000 IDR-20.000.000 IDR,4,4,4,4,1,2,2,0

In [ ]:
print(df['working hour'].unique())

['less than 40' '40-45' '51-55' '46-50' 'more than 56']

In [ ]:
# Convert to string
df['working hour'] = df['working hour'].astype(str)

# Define proper order mapping
working_hours_order = {
    'less than 40': 0,
    '40-45': 1,
    '46-50': 2,
    '51-55': 3,
    'more than 56': 4
}

# Apply mapping
df['working hour'] = df['working hour'].map(working_hours_order)

In [ ]:


display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,1,0,1,2,Senior lecturer,0,4,3,3,3,3,5.001.000IDR-10.000.000 IDR,3,3,3,3,3,3,3,1
1,1,1,0,1,Lecturer,0,3,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,4,4,3,2,2,2,0
2,3,1,2,3,Professor,1,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,4,4,4,4,4,4,1
3,4,1,2,3,Professor,3,3,4,4,4,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,5,5,4,1,1,2,0
4,1,1,1,1,Lecturer,1,3,2,5,3,4,3.000.000 IDR -5.000.000 IDR,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,0,2,Lecturer,0,5,5,5,5,5,3.000.000 IDR -5.000.000 IDR,5,5,4,5,2,2,2,0
522,2,0,1,1,Lecturer,3,2,2,3,2,2,3.000.000 IDR -5.000.000 IDR,2,3,2,1,5,5,5,1
523,2,1,2,2,Lecturer,3,4,2,5,4,4,5.001.000IDR-10.000.000 IDR,3,4,5,5,2,2,4,0
524,4,1,2,2,Senior lecturer,1,4,4,4,4,4,3.000.000 IDR -5.000.000 IDR,4,5,5,4,1,1,2,0
525,4,0,2,2,Lecturer,0,4,4,4,4,4,10.000.000 IDR-20.000.000 IDR,4,4,4,4,1,2,2,0

In [ ]:
print(df[' monthly salary'].unique())

['5.001.000IDR-10.000.000 IDR' '3.000.000 IDR -5.000.000 IDR'
 'Greater than 20.000.000 IDR (Lebih besar dari 20000 IDR)'
 '10.000.000 IDR-20.000.000 IDR']

In [ ]:


# Define proper order mapping
salary_order = {
    '3.000.000 IDR -5.000.000 IDR': 0,
    '5.001.000IDR-10.000.000 IDR': 1,
    '10.000.000 IDR-20.000.000 IDR': 2,
    'Greater than 20.000.000 IDR (Lebih besar dari 20000 IDR)': 3
}

# Apply mapping
df[' monthly salary'] = df[' monthly salary'].map(salary_order)

In [ ]:
display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,1,0,1,2,Senior lecturer,0,4,3,3,3,3,1,3,3,3,3,3,3,3,1
1,1,1,0,1,Lecturer,0,3,4,4,4,4,0,4,4,4,3,2,2,2,0
2,3,1,2,3,Professor,1,3,4,4,4,4,3,4,4,4,4,4,4,4,1
3,4,1,2,3,Professor,3,3,4,4,4,4,3,4,5,5,4,1,1,2,0
4,1,1,1,1,Lecturer,1,3,2,5,3,4,0,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,0,2,Lecturer,0,5,5,5,5,5,0,5,5,4,5,2,2,2,0
522,2,0,1,1,Lecturer,3,2,2,3,2,2,0,2,3,2,1,5,5,5,1
523,2,1,2,2,Lecturer,3,4,2,5,4,4,1,3,4,5,5,2,2,4,0
524,4,1,2,2,Senior lecturer,1,4,4,4,4,4,0,4,5,5,4,1,1,2,0
525,4,0,2,2,Lecturer,0,4,4,4,4,4,2,4,4,4,4,1,2,2,0

In [ ]:
print(df[ 'Job position'].unique())

['Senior lecturer' 'Lecturer ' 'Professor' 'Lecturer' 'Senior Lecturer'
 'Associate professor' 'senior lecturer' 'Associate professor ' 'lecturer'
 'Asscoiate professor ' ' lecturer']

In [ ]:
df['Job position'] = df['Job position'].astype(str).str.upper().str.strip()

In [ ]:
df['Job position'] = df['Job position'].replace({
    'ASSCOIATE PROFESSOR': 'ASSOCIATE PROFESSOR'
})

In [ ]:
print(df['Job position'].unique())

['SENIOR LECTURER' 'LECTURER' 'PROFESSOR' 'ASSOCIATE PROFESSOR']

In [ ]:
# Convert to string
df['Job position'] = df['Job position'].astype(str)



# Define proper order mapping
job_order = {
    'SENIOR LECTURER':1,
    'LECTURER': 0,
    'PROFESSOR':3,
    'ASSOCIATE PROFESSOR':2



}


# Apply mapping
df['Job position'] = df['Job position'].map(job_order)

In [ ]:
display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,1,0,1,2,1,0,4,3,3,3,3,1,3,3,3,3,3,3,3,1
1,1,1,0,1,0,0,3,4,4,4,4,0,4,4,4,3,2,2,2,0
2,3,1,2,3,3,1,3,4,4,4,4,3,4,4,4,4,4,4,4,1
3,4,1,2,3,3,3,3,4,4,4,4,3,4,5,5,4,1,1,2,0
4,1,1,1,1,0,1,3,2,5,3,4,0,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,0,2,0,0,5,5,5,5,5,0,5,5,4,5,2,2,2,0
522,2,0,1,1,0,3,2,2,3,2,2,0,2,3,2,1,5,5,5,1
523,2,1,2,2,0,3,4,2,5,4,4,1,3,4,5,5,2,2,4,0
524,4,1,2,2,1,1,4,4,4,4,4,0,4,5,5,4,1,1,2,0
525,4,0,2,2,0,0,4,4,4,4,4,2,4,4,4,4,1,2,2,0

In [ ]:
print(df.columns)

Index(['age', 'Gender', 'Work tenure', 'Education', 'Job position',
       'working hour', 'satisfaction with workload',
       'satisfied  compensation ', ' good relationship with peers ',
       ' satisfied with career and  opportunity',
       'satisfied with job profession ', ' monthly salary',
       ' satisfied with  work-life balance', ' work is meaningful ',
       'family support', ' mentally well and do not have anxiety ',
       '1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)',
       '2. In last 3 months, I am searching for  an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)',
       '3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)',
       'TOI (turnover intention)'],
      dtype='object')

In [ ]:
print(df['TOI (turnover intention)'].unique())

[1 0]

In [ ]:
print(df['TOI (turnover intention)'].isnull().any())

False

In [ ]:
print(df['TOI (turnover intention)'].isnull().sum())

0

In [ ]:
from imblearn.over_sampling import SMOTE

# Separate features and target
X = df.drop('TOI (turnover intention)', axis=1)
y = df['TOI (turnover intention)']

# Apply SMOTE
sm = SMOTE(random_state=42)
X_resampled, y_resampled = sm.fit_resample(X, y)

# Check the new distribution
print(y_resampled.value_counts())

TOI (turnover intention)
1    325
0    325
Name: count, dtype: int64

In [ ]:
# Re-bin family support into 2 categories (Low vs High)
df['family_support_bin'] = pd.cut(
    df['family support'],
    bins=[0,2,4,5],
    labels=[2,4,5])


df['peers_binned'] = pd.cut(df[' good relationship with peers '],
                            bins=[0,2,4,5],
                            labels=[2,4,5])

In [ ]:
display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,...,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention),family_support_bin,peers_binned
0,1,0,1,2,1,0,4,3,3,3,...,3,3,3,3,3,3,3,1,4,4
1,1,1,0,1,0,0,3,4,4,4,...,4,4,4,3,2,2,2,0,4,4
2,3,1,2,3,3,1,3,4,4,4,...,4,4,4,4,4,4,4,1,4,4
3,4,1,2,3,3,3,3,4,4,4,...,4,5,5,4,1,1,2,0,5,4
4,1,1,1,1,0,1,3,2,5,3,...,3,5,5,4,2,2,2,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,0,2,0,0,5,5,5,5,...,5,5,4,5,2,2,2,0,4,5
522,2,0,1,1,0,3,2,2,3,2,...,2,3,2,1,5,5,5,1,2,4
523,2,1,2,2,0,3,4,2,5,4,...,3,4,5,5,2,2,4,0,5,5
524,4,1,2,2,1,1,4,4,4,4,...,4,5,5,4,1,1,2,0,5,4
525,4,0,2,2,0,0,4,4,4,4,...,4,4,4,4,1,2,2,0,4,4

In [ ]:
# family support replace
df["family support"] = df["family_support_bin"]

# good relationship with peers replace
df[" good relationship with peers "] = df["peers_binned"]

# এখন শুধু helper columns drop করো
df = df.drop(columns=["family_support_bin", "peers_binned"])

print(df.head())

   age  Gender  Work tenure  Education  Job position  working hour  \
0    1       0            1          2             1             0
1    1       1            0          1             0             0
2    3       1            2          3             3             1
3    4       1            2          3             3             3
4    1       1            1          1             0             1

   satisfaction with workload  satisfied  compensation   \
0                           4                         3
1                           3                         4
2                           3                         4
3                           3                         4
4                           3                         2

   good relationship with peers    satisfied with career and  opportunity  \
0                              4                                        3
1                              4                                        4
2                              4                                        4
3                              4                                        4
4                              5                                        3

   satisfied with job profession    monthly salary  \
0                               3                1
1                               4                0
2                               4                3
3                               4                3
4                               4                0

    satisfied with  work-life balance   work is meaningful  family support  \
0                                   3                     3              4
1                                   4                     4              4
2                                   4                     4              4
3                                   4                     5              5
4                                   3                     5              5

    mentally well and do not have anxiety   \
0                                        3
1                                        3
2                                        4
3                                        4
4                                        4

   1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)  \
0                                                  3
1                                                  2
2                                                  4
3                                                  1
4                                                  2

   2. In last 3 months, I am searching for  an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)  \
0                                                  3
1                                                  2
2                                                  4
3                                                  1
4                                                  2

   3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)  \
0                                                  3
1                                                  2
2                                                  4
3                                                  2
4                                                  2

   TOI (turnover intention)
0                         1
1                         0
2                         1
3                         0
4                         0

In [ ]:
display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,1,0,1,2,1,0,4,3,4,3,3,1,3,3,4,3,3,3,3,1
1,1,1,0,1,0,0,3,4,4,4,4,0,4,4,4,3,2,2,2,0
2,3,1,2,3,3,1,3,4,4,4,4,3,4,4,4,4,4,4,4,1
3,4,1,2,3,3,3,3,4,4,4,4,3,4,5,5,4,1,1,2,0
4,1,1,1,1,0,1,3,2,5,3,4,0,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,0,2,0,0,5,5,5,5,5,0,5,5,4,5,2,2,2,0
522,2,0,1,1,0,3,2,2,4,2,2,0,2,3,2,1,5,5,5,1
523,2,1,2,2,0,3,4,2,5,4,4,1,3,4,5,5,2,2,4,0
524,4,1,2,2,1,1,4,4,4,4,4,0,4,5,5,4,1,1,2,0
525,4,0,2,2,0,0,4,4,4,4,4,2,4,4,4,4,1,2,2,0

In [ ]:
x_rep = df.iloc[:,0:16]
x_target = df.iloc[:,[-1]]

In [ ]:
display (x_rep)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety
0,1,0,1,2,1,0,4,3,4,3,3,1,3,3,4,3
1,1,1,0,1,0,0,3,4,4,4,4,0,4,4,4,3
2,3,1,2,3,3,1,3,4,4,4,4,3,4,4,4,4
3,4,1,2,3,3,3,3,4,4,4,4,3,4,5,5,4
4,1,1,1,1,0,1,3,2,5,3,4,0,3,5,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,0,2,0,0,5,5,5,5,5,0,5,5,4,5
522,2,0,1,1,0,3,2,2,4,2,2,0,2,3,2,1
523,2,1,2,2,0,3,4,2,5,4,4,1,3,4,5,5
524,4,1,2,2,1,1,4,4,4,4,4,0,4,5,5,4
525,4,0,2,2,0,0,4,4,4,4,4,2,4,4,4,4

In [ ]:
display (x_target)

     TOI (turnover intention)
0                           1
1                           0
2                           1
3                           0
4                           0
..                        ...
521                         0
522                         1
523                         0
524                         0
525                         0

[526 rows x 1 columns]

In [ ]:
df.dtypes.head(20)

age                                                                                                                                                                  int64
Gender                                                                                                                                                               int64
Work tenure                                                                                                                                                          int64
Education                                                                                                                                                            int64
Job position                                                                                                                                                         int64
working hour                                                                                                                                                         int64
satisfaction with workload                                                                                                                                           int64
satisfied  compensation                                                                                                                                              int64
 good relationship with peers                                                                                                                                     category
 satisfied with career and  opportunity                                                                                                                              int64
satisfied with job profession                                                                                                                                        int64
 monthly salary                                                                                                                                                      int64
 satisfied with  work-life balance                                                                                                                                   int64
 work is meaningful                                                                                                                                                  int64
family support                                                                                                                                                    category
 mentally well and do not have anxiety                                                                                                                               int64
1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)       int64
2. In last 3 months, I am searching for  an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)                                         int64
3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)                                                                 int64
TOI (turnover intention)                                                                                                                                             int64
dtype: object

In [ ]:
print(df.columns.tolist())

['age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour', 'satisfaction with workload', 'satisfied  compensation ', ' good relationship with peers ', ' satisfied with career and  opportunity', 'satisfied with job profession ', ' monthly salary', ' satisfied with  work-life balance', ' work is meaningful ', 'family support', ' mentally well and do not have anxiety ', '1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)', '2. In last 3 months, I am searching for  an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)', '3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)', 'TOI (turnover intention)']

In [ ]:
print(pd.crosstab(df['family support'], y))
print(pd.crosstab(df[' good relationship with peers '], y))

TOI (turnover intention)    0   1
family support
2                           8  92
4                         252  97
5                          65  12
TOI (turnover intention)          0    1
 good relationship with peers
2                                 5   67
4                               251  125
5                                69    9

In [ ]:
# # Re-bin family support into 2 categories (Low vs High)
# df['family_support_bin'] = pd.cut(
#     df['family support'],
#     bins=[0, 3, 5],   # 1–3 = Low, 4–5 = High
#     labels=[0, 1]
# ).astype(int)




# df['peers_binned'] = pd.cut(df[' good relationship with peers '],
#                             bins=[0,2,4,5],
#                             labels=[0,1,2])

In [ ]:
display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,1,0,1,2,1,0,4,3,4,3,3,1,3,3,4,3,3,3,3,1
1,1,1,0,1,0,0,3,4,4,4,4,0,4,4,4,3,2,2,2,0
2,3,1,2,3,3,1,3,4,4,4,4,3,4,4,4,4,4,4,4,1
3,4,1,2,3,3,3,3,4,4,4,4,3,4,5,5,4,1,1,2,0
4,1,1,1,1,0,1,3,2,5,3,4,0,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0,0,0,2,0,0,5,5,5,5,5,0,5,5,4,5,2,2,2,0
522,2,0,1,1,0,3,2,2,4,2,2,0,2,3,2,1,5,5,5,1
523,2,1,2,2,0,3,4,2,5,4,4,1,3,4,5,5,2,2,4,0
524,4,1,2,2,1,1,4,4,4,4,4,0,4,5,5,4,1,1,2,0
525,4,0,2,2,0,0,4,4,4,4,4,2,4,4,4,4,1,2,2,0

In [ ]:
import pandas as pd
import scipy.stats as stats

# Load dataset
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'
df = pd.read_csv(file_path)

# Clean column names (strip spaces)
df.columns = df.columns.str.strip()

# Features and target
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied  compensation ',
    'good relationship with peers', 'satisfied with career and  opportunity',
    'satisfied with job profession ', 'monthly salary',
    'satisfied with  work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

# Normalize feature names
features = [f.strip() for f in features]
target = target.strip()

# Chi-Square calculation
chi_results = []
for col in features:
    if col not in df.columns:
        continue
    contingency = pd.crosstab(df[col], df[target])
    chi2, p, _, _ = stats.chi2_contingency(contingency)
    chi_results.append([col, chi2, p])

# Create results table
chi_square_table = pd.DataFrame(
    chi_results, columns=["Feature", "Chi2", "p-value"]
).sort_values(by="Chi2", ascending=False).reset_index(drop=True)

# Show results
print(chi_square_table)

                                   Feature        Chi2       p-value
0               satisfaction with workload  260.130800  4.273685e-55
1    mentally well and do not have anxiety  221.432640  9.217851e-47
2        satisfied with  work-life balance  221.034705  1.122706e-46
3            satisfied with job profession  218.207880  4.899062e-47
4                  satisfied  compensation  215.451589  1.784903e-45
5   satisfied with career and  opportunity  196.795940  1.835194e-41
6                           family support  194.073987  7.059258e-41
7                       work is meaningful  179.963720  8.980506e-39
8             good relationship with peers  161.754571  7.664255e-35
9                             working hour  155.764546  1.183418e-32
10                                     age   41.350494  2.274146e-08
11                             Work tenure   33.301139  2.782391e-07
12                            Job position   23.863259  7.971734e-03
13                               Education   20.135328  5.284676e-03
14                          monthly salary    9.329574  2.521526e-02
15                                  Gender    2.639665  1.042255e-01

In [ ]:
# --- Setup ---
import pandas as pd
import numpy as np
from sklearn.feature_selection import f_classif
from sklearn.utils.validation import check_is_fitted

# 1) Load your CSV (adjust path if needed)
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'
df = pd.read_csv(file_path)

# 2) Clean column names a bit
df.columns = df.columns.str.strip()

# 3) Identify target and drop obvious junk columns if present
TARGET = 'TOI (turnover intention)'
drop_cols = ['Unnamed: 5']  # harmless empty column in your file
df = df.drop(columns=[c for c in drop_cols if c in df.columns], errors='ignore')

# 4) Guard: ensure target is 0/1 numeric
if not np.issubdtype(df[TARGET].dtype, np.number):
    # try to coerce
    df[TARGET] = pd.to_numeric(df[TARGET], errors='coerce')

# Drop rows where target is missing
df = df.dropna(subset=[TARGET])

# 5) Split X/y
X_raw = df.drop(columns=[TARGET])
y = df[TARGET].astype(int)

# 6) Decide which columns are numeric vs categorical.
#    - Numeric (Likert 1–5) stays numeric (good for ANOVA F)
#    - Non-numeric becomes one-hot encoded
numeric_cols = X_raw.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = [c for c in X_raw.columns if c not in numeric_cols]

# 7) One-hot encode categoricals with a SAFE separator so we can group back later
SAFE_SEP = '§'  # unlikely to appear in names
X_cat = pd.get_dummies(
    X_raw[categorical_cols],
    prefix=categorical_cols,
    prefix_sep=SAFE_SEP,
    drop_first=True,   # drop a baseline level to avoid perfect collinearity
    dtype=np.uint8
) if categorical_cols else pd.DataFrame(index=X_raw.index)

# 8) Combine numeric + encoded categoricals
X_num = X_raw[numeric_cols].copy()
X = pd.concat([X_num, X_cat], axis=1)

# Drop any rows with NaNs in features (rare, but safest for f_classif)
mask = X.notna().all(axis=1)
X = X.loc[mask]
y = y.loc[mask]

# 9) Run ANOVA F (univariate)
f_values, p_values = f_classif(X.values, y.values)

per_column = pd.DataFrame({
    'Column': X.columns,
    'F_value': f_values,
    'p_value': p_values
}).sort_values('F_value', ascending=False).reset_index(drop=True)

# 10) Aggregate back to original "Feature" (for dummies),
#     keeping numeric columns as-is.
#     We detect original feature for dummies by splitting on SAFE_SEP.
def original_feature(col: str) -> str:
    # if it contains the SAFE_SEP, the part before it is the original feature
    return col.split(SAFE_SEP, 1)[0] if SAFE_SEP in col else col

per_column['Feature'] = per_column['Column'].map(original_feature)

# Aggregate strategy:
# - For each original feature with multiple dummies:
#   * take max F_value (strongest signal among categories)
#   * take min p_value (most significant among categories)
# - For numeric features (no dummies), they remain single rows.
agg = (per_column
       .groupby('Feature', as_index=False)
       .agg(F_value_max=('F_value', 'max'),
            p_value_min=('p_value', 'min'),
            n_columns=('Column', 'count'))
       .sort_values('F_value_max', ascending=False)
       .reset_index(drop=True))

# 11) Display top results
print("\n=== ANOVA F (per column / dummy) — top 20 ===")
print(per_column.head(20))

print("\n=== ANOVA F (grouped back to original feature) ===")
print(agg)

=== ANOVA F (per column / dummy) — top 20 ===
                                               Column      F_value  \
0   2. In last 3 months, I am searching for  an al...  1231.078696
1   1. In last 3 months, I am thinking of quitting...  1216.023776
2   3. In last 3 months, I have low work motivatio...   654.964253
3                          satisfaction with workload   450.412687
4                       satisfied with job profession   329.670618
5                             satisfied  compensation   328.878742
6                   satisfied with  work-life balance   295.485226
7               mentally well and do not have anxiety   277.093544
8              satisfied with career and  opportunity   265.188107
9                                      family support   244.386499
10                                 work is meaningful   229.705426
11                       good relationship with peers   209.230822
12                                 working hour§51-55   126.492767
13                          working hour§less than 40    33.574664
14                     Work tenure§Less than 2 years     30.952897
15                          working hour§more than 56    24.537000
16                      Work tenure§more than 5 years    14.465791
17                              age§more than 56 year    10.030950
18                             Education§High School      8.259292
19                       Education§Bachelor's degree      7.919446

          p_value                                            Feature
0   1.196221e-139  2. In last 3 months, I am searching for  an al...
1   1.145139e-138  1. In last 3 months, I am thinking of quitting...
2    2.515828e-94  3. In last 3 months, I have low work motivatio...
3    1.326868e-72                         satisfaction with workload
4    1.637191e-57                      satisfied with job profession
5    2.089366e-57                            satisfied  compensation
6    7.570759e-53                  satisfied with  work-life balance
7    2.956912e-50              mentally well and do not have anxiety
8    1.516218e-48             satisfied with career and  opportunity
9    1.705984e-45                                     family support
10   2.730146e-43                                 work is meaningful
11   3.837615e-40                       good relationship with peers
12   1.947913e-26                                       working hour
13   1.184585e-08                                       working hour
14   4.222161e-08                                        Work tenure
15   9.850866e-07                                       working hour
16   1.595397e-04                                        Work tenure
17   1.628997e-03                                                age
18   4.218998e-03                                          Education
19   5.074458e-03                                          Education

=== ANOVA F (grouped back to original feature) ===
                                              Feature  F_value_max  \
0   2. In last 3 months, I am searching for  an al...  1231.078696
1   1. In last 3 months, I am thinking of quitting...  1216.023776
2   3. In last 3 months, I have low work motivatio...   654.964253
3                          satisfaction with workload   450.412687
4                       satisfied with job profession   329.670618
5                             satisfied  compensation   328.878742
6                   satisfied with  work-life balance   295.485226
7               mentally well and do not have anxiety   277.093544
8              satisfied with career and  opportunity   265.188107
9                                      family support   244.386499
10                                 work is meaningful   229.705426
11                       good relationship with peers   209.230822
12                                       working hour   126.492767
13                                        Work tenure    30.952897
14                                                age    10.030950
15                                          Education     8.259292
16                                       Job position     7.765880
17                                     monthly salary     6.633074
18                                             Gender     2.985434

      p_value_min  n_columns
0   1.196221e-139          1
1   1.145139e-138          1
2    2.515828e-94          1
3    1.326868e-72          1
4    1.637191e-57          1
5    2.089366e-57          1
6    7.570759e-53          1
7    2.956912e-50          1
8    1.516218e-48          1
9    1.705984e-45          1
10   2.730146e-43          1
11   3.837615e-40          1
12   1.947913e-26          4
13   4.222161e-08          3
14   1.628997e-03          4
15   4.218998e-03          7
16   5.517334e-03         10
17   1.028322e-02          3
18   8.460595e-02          1

In [ ]:
# import pandas as pd
# import numpy as np
# from sklearn.feature_selection import f_classif

# # ==== 1) Load & normalize column names ====
# file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'
# df = pd.read_csv(file_path)

# # normalize: strip ends + collapse multiple spaces to single
# df.columns = (
#     df.columns
#       .str.strip()
#       .str.replace(r'\s+', ' ', regex=True)
# )

# # ==== 2) Your features & target (use normalized names) ====
# features = [
#     'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
#     'satisfaction with workload', 'satisfied compensation',
#     'good relationship with peers', 'satisfied with career and opportunity',
#     'satisfied with job profession', 'monthly salary',
#     'satisfied with work-life balance', 'work is meaningful',
#     'family support', 'mentally well and do not have anxiety'
# ]
# target = 'TOI (turnover intention)'

# # keep only your requested columns (and report if anything is missing)
# need_cols = features + [target]
# missing = [c for c in need_cols if c not in df.columns]
# if missing:
#     raise KeyError(f"These columns are missing after normalization: {missing}")

# df = df[need_cols].dropna(subset=[target])
# y = df[target]

# # ==== 3) Split numeric vs categorical from YOUR list ====
# # Likert (1–5) numeric/ordinal features:
# numeric_features = [
#     'satisfaction with workload', 'satisfied compensation',
#     'good relationship with peers', 'satisfied with career and opportunity',
#     'satisfied with job profession', 'satisfied with work-life balance',
#     'work is meaningful', 'family support',
#     'mentally well and do not have anxiety'
# ]
# categorical_features = [c for c in features if c not in numeric_features]

# # Sanity cast: numeric columns must be numeric
# X_num = df[numeric_features].apply(pd.to_numeric, errors='coerce')
# # if any NaNs remain in numeric features, drop those rows (keeps f_classif happy)
# row_mask = X_num.notna().all(axis=1)
# X_num = X_num.loc[row_mask]
# y_num = y.loc[row_mask]

# # ==== 4) One-hot encode categorical features (then combine with numeric) ====
# SAFE_SEP = '§'  # safe separator to recover original feature name
# if categorical_features:
#     X_cat_raw = df.loc[row_mask, categorical_features].copy()
#     X_cat = pd.get_dummies(
#         X_cat_raw,
#         prefix=categorical_features,
#         prefix_sep=SAFE_SEP,
#         drop_first=True,   # drop baseline per categorical feature
#         dtype=np.uint8
#     )
# else:
#     X_cat = pd.DataFrame(index=X_num.index)

# # Combined design matrix for ANOVA F
# X_all = pd.concat([X_num, X_cat], axis=1)

# # Drop any remaining rows with NaNs (should be rare)
# mask_all = X_all.notna().all(axis=1)
# X_all = X_all.loc[mask_all]
# y_all = y_num.loc[mask_all]

# # ==== 5) Run ANOVA F (univariate) across ALL columns (numeric + dummies) ====
# f_vals, p_vals = f_classif(X_all.values, y_all.values)

# per_column = pd.DataFrame({
#     'Column': X_all.columns,
#     'F_value': f_vals,
#     'p_value': p_vals
# }).sort_values('F_value', ascending=False).reset_index(drop=True)

# # ==== 6) Group back to ORIGINAL feature name (for dummies) ====
# def original_feature_name(col: str) -> str:
#     # if one-hot dummy: "Feature§Category"
#     return col.split(SAFE_SEP, 1)[0] if SAFE_SEP in col else col

# per_column['Feature'] = per_column['Column'].map(original_feature_name)

# # aggregate per original feature:
# # - max F_value among its columns (strongest signal)
# # - min p_value among its columns (most significant)
# # - n_columns = number of columns contributed by that feature (1 for numeric)
# grouped = (
#     per_column
#     .groupby('Feature', as_index=False)
#     .agg(F_value_max=('F_value', 'max'),
#          p_value_min=('p_value', 'min'),
#          n_columns=('Column', 'count'))
#     .sort_values('F_value_max', ascending=False)
#     .reset_index(drop=True)
# )

# # ==== 7) Display results ====
# print("=== ANOVA F (per column: numeric + one-hot dummies) — Top 25 ===")
# print(per_column.head(25))
# print("\n=== ANOVA F (grouped back to original feature) ===")
# print(grouped)

# # Optionally save to CSV in Colab
# per_column.to_csv('/content/anova_f_per_column.csv', index=False)
# grouped.to_csv('/content/anova_f_grouped_by_feature.csv', index=False)
# print("\nSaved: /content/anova_f_per_column.csv  and  /content/anova_f_grouped_by_feature.csv")

# # Helpful summary about expansion
# print("\nCategorical features expanded:",
#       {f: sum(per_column['Feature'].eq(f)) for f in categorical_features})
# print("Numeric features kept as-is:", numeric_features)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import OrdinalEncoder

# 1) Load and normalize column names
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'
df = pd.read_csv(file_path)
df.columns = (
    df.columns
      .str.strip()
      .str.replace(r'\s+', ' ', regex=True)
)

# 2) Your features and target
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

# Keep only requested cols (drop rows missing target)
df = df[features + [target]].dropna(subset=[target])

# 3) Split categorical vs numeric from YOUR list
categorical_features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position',
    'working hour', 'monthly salary'
]
numeric_features = [c for c in features if c not in categorical_features]

# 4) Prepare X: encode categoricals, keep numeric as numeric
X_cat = df[categorical_features].astype('category')
X_num = df[numeric_features].apply(pd.to_numeric, errors='coerce')

# Drop rows with NaNs in numeric features to satisfy MI
row_mask = X_num.notna().all(axis=1)
X_cat = X_cat.loc[row_mask]
X_num = X_num.loc[row_mask]
y = df.loc[row_mask, target].astype(int)

# Ordinal-encode categoricals (just to convert strings→ints)
enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_cat_enc = pd.DataFrame(
    enc.fit_transform(X_cat),
    columns=categorical_features,
    index=X_cat.index
).astype(int)

# Combine back
X = pd.concat([X_cat_enc, X_num], axis=1)

# 5) Build the discrete_features mask (True for categoricals, False for numeric)
discrete_mask = [col in categorical_features for col in X.columns]

# 6) Run Mutual Information
mi_scores = mutual_info_classif(
    X.values, y.values,
    discrete_features=discrete_mask,
    random_state=42
)

mi_table = pd.DataFrame({
    "Feature": X.columns,
    "MI Score": mi_scores,
    "Type": ["categorical" if d else "numeric" for d in discrete_mask]
}).sort_values("MI Score", ascending=False).reset_index(drop=True)

print(mi_table)

                                  Feature  MI Score         Type
0              satisfaction with workload  0.260661      numeric
1        satisfied with work-life balance  0.256384      numeric
2           satisfied with job profession  0.232816      numeric
3                  satisfied compensation  0.229535      numeric
4   mentally well and do not have anxiety  0.218119      numeric
5   satisfied with career and opportunity  0.197362      numeric
6                          family support  0.180731      numeric
7                      work is meaningful  0.171876      numeric
8                            working hour  0.152510  categorical
9            good relationship with peers  0.139234      numeric
10                                    age  0.039701  categorical
11                            Work tenure  0.031212  categorical
12                           Job position  0.024117  categorical
13                              Education  0.020771  categorical
14                         monthly salary  0.009054  categorical
15                                 Gender  0.002803  categorical

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import OrdinalEncoder

# === 1) Load & normalize column names ===
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'  # <- adjust if needed
df = pd.read_csv(file_path)
df.columns = (
    df.columns
      .str.strip()
      .str.replace(r'\s+', ' ', regex=True)
)

# === 2) Your features & target (normalized names) ===
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

# Keep only requested columns and drop rows missing target
df = df[features + [target]].dropna(subset=[target])

# === 3) Split categorical vs numeric from YOUR list ===
categorical_features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position',
    'working hour', 'monthly salary'
]
numeric_features = [c for c in features if c not in categorical_features]

# Prepare X: encode categoricals, keep numeric as numeric
X_cat = df[categorical_features].astype('category')
X_num = df[numeric_features].apply(pd.to_numeric, errors='coerce')

# Drop rows with NaNs in numeric features (keeps MI happy)
row_mask = X_num.notna().all(axis=1)
X_cat = X_cat.loc[row_mask]
X_num = X_num.loc[row_mask]
y = df.loc[row_mask, target].astype(int)

enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_cat_enc = pd.DataFrame(
    enc.fit_transform(X_cat),
    columns=categorical_features,
    index=X_cat.index
).astype(int)

# Combine back
X = pd.concat([X_cat_enc, X_num], axis=1)

# Build the discrete_features mask (True for categoricals, False for numeric)
discrete_mask = [col in categorical_features for col in X.columns]

# === 4) Information Gain (Mutual Information) ===
IG_scores = mutual_info_classif(
    X.values, y.values,
    discrete_features=discrete_mask,
    random_state=42
)

ig_table = pd.DataFrame({
    "Feature": X.columns,
    "Information_Gain": IG_scores,
    "Type": ["categorical" if d else "numeric" for d in discrete_mask]
}).sort_values("Information_Gain", ascending=False).reset_index(drop=True)

print(ig_table)

# Optional: save to CSV
ig_table.to_csv('/content/information_gain_scores.csv', index=False)
print("\nSaved: /content/information_gain_scores.csv")

                                  Feature  Information_Gain         Type
0              satisfaction with workload          0.260661      numeric
1        satisfied with work-life balance          0.256384      numeric
2           satisfied with job profession          0.232816      numeric
3                  satisfied compensation          0.229535      numeric
4   mentally well and do not have anxiety          0.218119      numeric
5   satisfied with career and opportunity          0.197362      numeric
6                          family support          0.180731      numeric
7                      work is meaningful          0.171876      numeric
8                            working hour          0.152510  categorical
9            good relationship with peers          0.139234      numeric
10                                    age          0.039701  categorical
11                            Work tenure          0.031212  categorical
12                           Job position          0.024117  categorical
13                              Education          0.020771  categorical
14                         monthly salary          0.009054  categorical
15                                 Gender          0.002803  categorical

Saved: /content/information_gain_scores.csv

In [ ]:
# from sklearn.feature_selection import chi2
# import pandas as pd

# # Separate features (first 16 columns) and target (last column)
# X = df.iloc[:, 0:16]
# y = df.iloc[:, -1]

# # Chi-Square Test
# chi_scores, p_values = chi2(X, y)

# # Results as DataFrame
# chi2_results = pd.DataFrame({
#     "Feature": X.columns,
#     "Chi2 Score": chi_scores,
#     "p-value": p_values
# }).sort_values(by="Chi2 Score", ascending=False)

# print(chi2_results)

In [ ]:
# from scipy.stats import chi2_contingency
# import pandas as pd

# # Separate features (first 16 columns) and target (last column)
# X = df.iloc[:, 0:16]
# y = df.iloc[:, -1]

# # Store results
# results = []

# for col in X.columns:
#     contingency = pd.crosstab(X[col], y)
#     chi2_stat, p, dof, expected = chi2_contingency(contingency)
#     results.append({
#         'Feature': col,
#         'Chi2 Score': chi2_stat,
#         'p-value': p
#     })

# # Make a DataFrame
# chi2_results_ct = pd.DataFrame(results).sort_values(by='Chi2 Score', ascending=False)

# print(chi2_results_ct)

In [ ]:
# from sklearn.feature_selection import f_classif
# import pandas as pd

# # Features (first 16 cols) and target (last col)
# X = df.iloc[:, 0:16]
# y = df.iloc[:, -1]

# # ANOVA F-test
# f_scores, p_values = f_classif(X, y)

# # Results DataFrame
# anova_results = pd.DataFrame({
#     "Feature": X.columns,
#     "F Score": f_scores,
#     "p-value": p_values
# }).sort_values(by="F Score", ascending=False)

# print(anova_results)

In [ ]:
# from sklearn.feature_selection import mutual_info_classif
# import pandas as pd

# # Features and target
# X = df.iloc[:, 0:16]
# y = df.iloc[:, -1]

# # Mutual Information (classification)
# mi_scores = mutual_info_classif(X, y, discrete_features=True, random_state=42)

# # Results DataFrame
# mi_results = pd.DataFrame({
#     "Feature": X.columns,
#     "MI Score": mi_scores
# }).sort_values(by="MI Score", ascending=False)

# print(mi_results)

In [ ]:
# from sklearn.feature_selection import mutual_info_classif
# import pandas as pd

# # Features (first 16) and target (last col)
# X = df.iloc[:, 0:16]
# y = df.iloc[:, -1]

# # Information Gain = Mutual Information
# ig_scores = mutual_info_classif(X, y, discrete_features=True, random_state=42)

# # Results DataFrame
# ig_results = pd.DataFrame({
#     "Feature": X.columns,
#     "Information Gain": ig_scores
# }).sort_values(by="Information Gain", ascending=False)

# print(ig_results)

In [ ]:
from sklearn.feature_selection import chi2, f_classif, mutual_info_classif
import pandas as pd

# Features & target
X = df.iloc[:, 0:16]
y = df.iloc[:, -1]

# --- Chi2 ---
chi_scores, chi_p = chi2(X, y)

# --- ANOVA F-test ---
f_scores, f_p = f_classif(X, y)

# --- Mutual Information (same as Information Gain here) ---
mi_scores = mutual_info_classif(X, y, discrete_features=True, random_state=42)

# --- Combine results ---
results = pd.DataFrame({
    "Feature": X.columns,
    "Chi2": chi_scores,
    "ANOVA_F": f_scores,
    "Mutual_Info": mi_scores,
    "Info_Gain": mi_scores   # same values, different name
})

# --- Min-Max Normalization for each metric ---
for col in ["Chi2", "ANOVA_F", "Mutual_Info", "Info_Gain"]:
    col_min, col_max = results[col].min(), results[col].max()
    if col_max - col_min == 0:
        results[col + "_Norm"] = 0.0
    else:
        results[col + "_Norm"] = (results[col] - col_min) / (col_max - col_min)

# --- Final Table ---
final_results = results[["Feature",
                         "Chi2_Norm",
                         "ANOVA_F_Norm",
                         "Mutual_Info_Norm",
                         "Info_Gain_Norm"]]

print(final_results.sort_values(by="Chi2_Norm", ascending=False))

ValueError: could not convert string to float: '26-35 year'

In [ ]:
# from sklearn.feature_selection import chi2, f_classif, mutual_info_classif
# import pandas as pd

# # Features & target
# X = df.iloc[:, 0:16]
# y = df.iloc[:, -1]

# # --- Chi2 ---
# chi_scores, chi_p = chi2(X, y)

# # --- ANOVA F-test ---
# f_scores, f_p = f_classif(X, y)

# # --- Mutual Information / Information Gain ---
# mi_scores = mutual_info_classif(X, y, discrete_features=True, random_state=42)

# # --- Combine results ---
# results = pd.DataFrame({
#     "Feature": X.columns,
#     "Chi2": chi_scores,
#     "ANOVA_F": f_scores,
#     "Mutual_Info": mi_scores,
#     "Info_Gain": mi_scores   # same values
# })

# # --- Min-Max Normalization ---
# for col in ["Chi2", "ANOVA_F", "Mutual_Info", "Info_Gain"]:
#     col_min, col_max = results[col].min(), results[col].max()
#     if col_max - col_min == 0:
#         results[col + "_Norm"] = 0.0
#     else:
#         results[col + "_Norm"] = (results[col] - col_min) / (col_max - col_min)

# # --- Average of normalized scores (MF) ---
# results["MF"] = results[["Chi2_Norm", "ANOVA_F_Norm", "Mutual_Info_Norm", "Info_Gain_Norm"]].mean(axis=1)

# # --- Final Table ---
# final_results = results[["Feature",
#                          "Chi2_Norm",
#                          "ANOVA_F_Norm",
#                          "Mutual_Info_Norm",
#                          "Info_Gain_Norm",
#                          "MF"]]

# print(final_results.sort_values(by="MF", ascending=False))

In [ ]:
# print("X shape:", X.shape)
# print("coef shape:", lasso_clf.named_steps[
#   "logit"].coef_.shape)

In [ ]:
# coef = np.abs(lasso_clf.named_steps["logit"].coef_[0])  # keep the 1D array
# print(len(coef), len(X.columns))  # sanity check

In [ ]:
# lasso_imp = pd.DataFrame({
#     "Feature": X.columns,
#     "Lasso_Importance": coef
# }).sort_values("Lasso_Importance", ascending=False)

# print(lasso_imp)

In [ ]:
# # from sklearn.linear_model import LogisticRegressionCV
# # from sklearn.preprocessing import StandardScaler
# # from sklearn.pipeline import Pipeline
# # from sklearn.model_selection import StratifiedKFold
# # import numpy as np
# # import pandas as pd

# # # Split features/target
# # X = df.iloc[:, 0:16].copy()
# # y = df.iloc[:, -1].copy()

# # # Pipeline: Standardize -> L1 Logistic with CV
# # lasso_clf = Pipeline([
# #     ("scaler", StandardScaler(with_mean=True, with_std=True)),
# #     ("logit", LogisticRegressionCV(
# #         Cs=np.logspace(-3, 3, 15),
# #         cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
# #         penalty="l1",
# #         solver="liblinear",
# #         scoring="f1_macro",
# #         max_iter=2000,
# #         n_jobs=-1,
# #         refit=True
# #     ))
# # ])

# # lasso_clf.fit(X, y)

# # # Absolute coefficient magnitude = importance
# # coef = np.abs(lasso_clf.named_steps["logit"].coef_).ravel()
# # lasso_imp = pd.DataFrame({
# #     "Feature": X.columns,
# #     "Lasso_Importance": coef
# # }).sort_values("Lasso_Importance", ascending=False)

# # print(lasso_imp)

# from sklearn.linear_model import LogisticRegressionCV
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import Pipeline
# from sklearn.model_selection import StratifiedKFold
# import numpy as np
# import pandas as pd

# # ----------------------------
# # Split features / target
# # ----------------------------
# X = df.iloc[:, 0:16].copy()  # features
# y = df.iloc[:, -1].copy()    # target

# # ----------------------------
# # Pipeline: Standardize -> L1 LogisticRegressionCV
# # ----------------------------
# lasso_clf = Pipeline([
#     ("scaler", StandardScaler(with_mean=True, with_std=True)),
#     ("logit", LogisticRegressionCV(
#         Cs=np.logspace(-3, 3, 15),
#         cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
#         penalty="l1",
#         solver="liblinear",
#         scoring="f1_macro",
#         max_iter=2000,
#         n_jobs=-1,
#         refit=True
#     ))
# ])

# # Fit the model
# lasso_clf.fit(X, y)

# # ----------------------------
# # Feature importance
# # ----------------------------
# # Get absolute coefficients
# coefs = np.abs(lasso_clf.named_steps["logit"].coef_)

# # Aggregate across classes (max magnitude for each feature)
# if coefs.shape[0] > 1:  # multi-class
#     coef_agg = coefs.max(axis=0)
# else:  # binary
#     coef_agg = coefs.ravel()

# # Build importance DataFrame
# lasso_imp = pd.DataFrame({
#     "Feature": X.columns,
#     "Lasso_Importance": coef_agg
# }).sort_values("Lasso_Importance", ascending=False).reset_index(drop=True)

# # ----------------------------
# # Show results
# # ----------------------------
# print(lasso_imp)

In [ ]:
# ===== LASSO (L1 Logistic) feature selection for TOI =====
# - Uses ONLY your declared features + target
# - One-hot encodes categoricals, scales Likert numerics
# - Cross-validated strength of regularization (C)
# - Produces per-column and grouped-by-feature tables and saves as CSVs

import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegressionCV

print("scikit-learn version:", sklearn.__version__)

# ---------- 1) Load & normalize column names ----------
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'  # <-- adjust if needed
df = pd.read_csv(file_path)
# strip ends & collapse multiple spaces to a single space (your CSV has extra spaces)
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

# ---------- 2) Your features and target (normalized names) ----------
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

# keep only your columns; drop rows with missing target
missing = [c for c in features + [target] if c not in df.columns]
if missing:
    raise KeyError(f"Missing columns after normalization: {missing}")

df = df[features + [target]].dropna(subset=[target])
y = df[target].astype(int)

# ---------- 3) Split numeric (Likert) vs categorical ----------
categorical_features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position',
    'working hour', 'monthly salary'
]
numeric_features = [c for c in features if c not in categorical_features]

# ensure Likert numerics are numeric
for col in numeric_features:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# drop rows with any missing in selected features
df = df.dropna(subset=features)
X = df[features]
y = df[target].astype(int)

# ---------- 4) Preprocessing: OHE for categoricals + scaling for numerics ----------
SAFE_SEP = '§'  # used to rebuild original feature names from dummies later

# Handle OneHotEncoder API differences across sklearn versions
# - <1.2: OneHotEncoder(..., sparse=False)
# - >=1.2: OneHotEncoder(..., sparse_output=False)
ohe_kwargs = dict(drop='first', handle_unknown='ignore')
ver = tuple(int(v) for v in sklearn.__version__.split('.')[:2])
if ver >= (1, 2):
    ohe_kwargs['sparse_output'] = False
else:
    ohe_kwargs['sparse'] = False

ohe = OneHotEncoder(**ohe_kwargs)
scaler = StandardScaler()

preprocess = ColumnTransformer(
    transformers=[
        ('cat', ohe, categorical_features),
        ('num', scaler, numeric_features),
    ],
    remainder='drop'
)

# ---------- 5) L1-penalized Logistic Regression with CV ----------
# We optimize F1 and use class_weight='balanced' for any class imbalance.
logreg_cv = LogisticRegressionCV(
    Cs=np.logspace(-2, 1, 8),  # search range for C (inverse of regularization)
    cv=StratifiedKFold(n_splits=3, shuffle=True, random_state=42),
    penalty='l1',
    solver='saga',             # supports l1 with class_weight
    scoring='f1',
    class_weight='balanced',
    max_iter=4000,
    n_jobs=-1,
    refit=True
)

pipe = Pipeline(steps=[('prep', preprocess), ('clf', logreg_cv)])
pipe.fit(X, y)

# ---------- 6) Recover feature names after preprocessing ----------
# Build Feature§Category names for one-hot columns so we can group later.
cat_feature_names = []
ohe_fitted = pipe.named_steps['prep'].named_transformers_['cat']
for feat, cats in zip(categorical_features, ohe_fitted.categories_):
    # drop='first' => first category is the baseline and not present in output
    for cat in cats[1:]:
        cat_feature_names.append(f"{feat}{SAFE_SEP}{cat}")

num_feature_names = numeric_features[:]  # unchanged by StandardScaler
all_feature_names = cat_feature_names + num_feature_names

# ---------- 7) Coefficients (LASSO shrinkage; zeros mean dropped) ----------
coefs = pipe.named_steps['clf'].coef_.ravel()
per_column = pd.DataFrame({
    'Column': all_feature_names,
    'Coefficient': coefs
})
per_column['Abs_Coeff'] = per_column['Coefficient'].abs()
per_column = per_column.sort_values('Abs_Coeff', ascending=False).reset_index(drop=True)

def original_feature_name(col: str) -> str:
    return col.split(SAFE_SEP, 1)[0] if SAFE_SEP in col else col

per_column['Feature'] = per_column['Column'].map(original_feature_name)

# Aggregate back to original feature:
# - Importance = sum of |coefficients| over its columns
# - NonZero_Columns = count of nonzero coefficients (survived lasso)
# - Max_Abs = largest |coef| among its columns
# - Columns = total columns contributed (1 for numeric; >1 for categoricals)
grouped = (
    per_column
    .groupby('Feature', as_index=False)
    .agg(Importance=('Abs_Coeff', 'sum'),
         NonZero_Columns=('Coefficient', lambda x: int(np.sum(x != 0))),
         Max_Abs=('Abs_Coeff', 'max'),
         Columns=('Column', 'count'))
    .sort_values('Importance', ascending=False)
    .reset_index(drop=True)
)

# ---------- 8) Show & save ----------
print("\n=== L1-Logistic (LASSO) — Per Column Coefficients (top 25) ===")
print(per_column.head(25))
print("\n=== L1-Logistic (LASSO) — Grouped by Feature ===")
print(grouped)

per_column.to_csv('/content/lasso_per_column.csv', index=False)
grouped.to_csv('/content/lasso_grouped_by_feature.csv', index=False)
print("\nSaved CSVs:\n  /content/lasso_per_column.csv\n  /content/lasso_grouped_by_feature.csv")

# Optional: quick glance at class balance
print("\nClass counts (TOI):")
print(y.value_counts())

In [ ]:
# from sklearn.ensemble import RandomForestClassifier
# import pandas as pd

# # Features/target
# X = df.iloc[:, 0:16].copy()
# y = df.iloc[:, -1].copy()

# # Train RF
# rf = RandomForestClassifier(
#     n_estimators=500,
#     random_state=42,
#     class_weight="balanced",
#     n_jobs=-1
# )

# rf.fit(X, y)

# rf_imp = pd.DataFrame({
#     "Feature": X.columns,
#     "RF_Importance": rf.feature_importances_
# }).sort_values("RF_Importance", ascending=False)

# print(rf_imp)

In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance

# 1) Load & clean
df = pd.read_csv('/content/Final Primary_dataset_from_Indonesian_Private_University.csv')
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

df = df[features + [target]].dropna(subset=[target])
y = df[target].astype(int)

# 2) Split categorical vs numeric (Likert)
categorical = ['age','Gender','Work tenure','Education','Job position','working hour','monthly salary']
numeric = [c for c in features if c not in categorical]
for c in numeric:
    df[c] = pd.to_numeric(df[c], errors='coerce')
df = df.dropna(subset=features)

X = df[features]; y = df[target].astype(int)

# 3) Train/validation split (permutation importance on val set)
X_tr, X_val, y_tr, y_val = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

# 4) One-hot encode categoricals (dense)
ohe_kwargs = dict(drop='first', handle_unknown='ignore')
ver = tuple(int(v) for v in sklearn.__version__.split('.')[:2])
if ver >= (1, 2):
    ohe_kwargs['sparse_output'] = False
else:
    ohe_kwargs['sparse'] = False

ohe = OneHotEncoder(**ohe_kwargs)
pre = ColumnTransformer(
    transformers=[
        ('cat', ohe, categorical),
        ('num', 'passthrough', numeric),
    ],
    remainder='drop'
)

# Fit transform
Xtr_enc = pre.fit_transform(X_tr)
Xval_enc = pre.transform(X_val)

# Encoded feature names (Feature§Category for dummies)
SAFE_SEP = '§'
cat_names = []
for feat, cats in zip(categorical, pre.named_transformers_['cat'].categories_):
    for cat in cats[1:]:  # drop='first' baseline omitted
        cat_names.append(f"{feat}{SAFE_SEP}{cat}")
enc_feature_names = cat_names + numeric

# 5) Random Forest
rf = RandomForestClassifier(
    n_estimators=400,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
rf.fit(Xtr_enc, y_tr)

# 6) MDI importance
mdi = pd.DataFrame({
    'Column': enc_feature_names,
    'MDI_Importance': rf.feature_importances_
}).sort_values('MDI_Importance', ascending=False).reset_index(drop=True)

# 7) Permutation importance (on validation set) with F1
perm = permutation_importance(rf, Xval_enc, y_val, scoring='f1', n_repeats=20, random_state=42, n_jobs=-1)
perm_df = pd.DataFrame({
    'Column': enc_feature_names,
    'Perm_Importance': perm.importances_mean,
    'Perm_Std': perm.importances_std
}).sort_values('Perm_Importance', ascending=False).reset_index(drop=True)

# 8) Group back to original features
def orig(col): return col.split(SAFE_SEP, 1)[0] if SAFE_SEP in col else col
mdi['Feature'] = mdi['Column'].map(orig)
perm_df['Feature'] = perm_df['Column'].map(orig)

mdi_grouped = (mdi.groupby('Feature', as_index=False)
                 .agg(MDI_Importance_sum=('MDI_Importance','sum'),
                      Columns=('Column','count'))
                 .sort_values('MDI_Importance_sum', ascending=False))

perm_grouped = (perm_df.groupby('Feature', as_index=False)
                  .agg(Perm_Importance_sum=('Perm_Importance','sum'),
                       Perm_Std_sum=('Perm_Std','sum'),
                       Columns=('Column','count'))
                  .sort_values('Perm_Importance_sum', ascending=False))

print("MDI per column (top 20):\n", mdi.head(20))
print("\nPermutation per column (top 20):\n", perm_df.head(20))
print("\nMDI grouped:\n", mdi_grouped)
print("\nPermutation grouped:\n", perm_grouped)

In [ ]:
# from sklearn.linear_model import LogisticRegressionCV
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import Pipeline
# from sklearn.model_selection import StratifiedKFold
# from sklearn.ensemble import RandomForestClassifier
# import numpy as np
# import pandas as pd

# # Features & target
# X = df.iloc[:, 0:16].copy()
# y = df.iloc[:, -1].copy()

# # ----- LASSO (L1 Logistic Regression) -----
# lasso_clf = Pipeline([
#     ("scaler", StandardScaler(with_mean=True, with_std=True)),
#     ("logit", LogisticRegressionCV(
#         Cs=np.logspace(-3, 3, 15),
#         cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
#         penalty="l1",
#         solver="liblinear",
#         scoring="f1_macro",
#         max_iter=2000,
#         n_jobs=-1,
#         refit=True
#     ))
# ])

# lasso_clf.fit(X, y)

# # Handle multi-class coefficients
# coefs = np.abs(lasso_clf.named_steps["logit"].coef_)
# if coefs.shape[0] > 1:  # multi-class
#     lasso_coef = coefs.max(axis=0)
# else:  # binary
#     lasso_coef = coefs.ravel()

# lasso_imp = pd.DataFrame({
#     "Feature": X.columns,
#     "Lasso_Importance": lasso_coef
# })

# # ----- RandomForest -----
# rf = RandomForestClassifier(
#     n_estimators=500,
#     random_state=42,
#     class_weight="balanced",
#     n_jobs=-1
# )
# rf.fit(X, y)

# rf_imp = pd.DataFrame({
#     "Feature": X.columns,
#     "RF_Importance": rf.feature_importances_
# })

# # ----- Merge results -----
# results = pd.merge(lasso_imp, rf_imp, on="Feature")

# # ----- Min-Max normalization -----
# for col in ["Lasso_Importance", "RF_Importance"]:
#     cmin, cmax = results[col].min(), results[col].max()
#     if cmax - cmin == 0:
#         results[col + "_Norm"] = 0.0
#     else:
#         results[col + "_Norm"] = (results[col] - cmin) / (cmax - cmin)

# # ----- Average of normalized scores (ME) -----
# results["ME"] = results[["Lasso_Importance_Norm", "RF_Importance_Norm"]].mean(axis=1)

# # ----- Sort by ME -----
# final_results = results.sort_values("ME", ascending=False).reset_index(drop=True)

# print(final_results)

In [ ]:
# from sklearn.feature_selection import RFE
# from sklearn.linear_model import LogisticRegression
# import pandas as pd

# # Features & target
# X = df.iloc[:, 0:16].copy()
# y = df.iloc[:, -1].copy()

# # Base estimator
# base_est = LogisticRegression(solver="liblinear", class_weight="balanced", max_iter=2000, random_state=42)

# # RFE
# rfe = RFE(estimator=base_est, n_features_to_select=8)
# rfe.fit(X, y)

# # RFE rank
# rfe_rank = rfe.ranking_
# max_rank = rfe_rank.max()

# # RFE score
# rfe_score = (max_rank - rfe_rank + 1)

# rfe_results = pd.DataFrame({
#     "Feature": X.columns,
#     "RFE_Rank": rfe_rank,
#     "RFE_Score": rfe_score
# }).sort_values("RFE_Rank")

# print(rfe_results)

In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

# --- Load & normalize column names ---
df = pd.read_csv('/content/Final Primary_dataset_from_Indonesian_Private_University.csv')
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

# --- Your exact features & target ---
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

# keep only these columns
df = df[features + [target]].dropna(subset=[target])
y = df[target].astype(int)

# split your feature types
categorical = ['age','Gender','Work tenure','Education','Job position','working hour','monthly salary']
numeric = [c for c in features if c not in categorical]

# ensure Likert numerics are numeric
for c in numeric:
    df[c] = pd.to_numeric(df[c], errors='coerce')
df = df.dropna(subset=features)

X = df[features]
y = df[target].astype(int)

# --- Version-safe OneHotEncoder (dense output) ---
ver = tuple(int(v) for v in sklearn.__version__.split('.')[:2])
ohe_kwargs = dict(drop='first', handle_unknown='ignore')
if ver >= (1, 2):
    ohe_kwargs['sparse_output'] = False
else:
    ohe_kwargs['sparse'] = False

ohe = OneHotEncoder(**ohe_kwargs)
scaler = StandardScaler()

preprocess = ColumnTransformer(
    transformers=[
        ('cat', ohe, categorical),
        ('num', scaler, numeric),
    ],
    remainder='drop'
)

# --- Base estimator for RFE ---
# (L2 is stable for ranking; class_weight helps imbalance)
est = LogisticRegression(
    solver='liblinear',
    penalty='l2',
    class_weight='balanced',
    max_iter=2000,
    random_state=42
)

# --- RFE: select top k; but we’ll inspect ranks for ALL columns ---
rfe = RFE(estimator=est, n_features_to_select=8, step=1)

pipe = Pipeline([('prep', preprocess), ('rfe', rfe)])
pipe.fit(X, y)

# --- Recover encoded feature names (dummies + numeric) ---
# refit an encoder on X[categorical] to get categories in consistent order
# Use the same kwargs we built earlier (already has drop + handle_unknown)
ohe_tmp = OneHotEncoder(**ohe_kwargs).fit(X[categorical])

cat_names = []
for feat, cats in zip(categorical, ohe_tmp.categories_):
    for cat in cats[1:]:  # drop='first' -> first category omitted
        cat_names.append(f"{feat}={cat}")


enc_feature_names = cat_names + numeric

# --- RFE outputs ---
support = pipe.named_steps['rfe'].support_          # True for selected
ranking = pipe.named_steps['rfe'].ranking_          # 1 = best (kept), 2,3,... eliminated earlier

rfe_results = pd.DataFrame({
    "Encoded_Feature": enc_feature_names,
    "Selected": support,
    "RFE_Rank": ranking
}).sort_values(["RFE_Rank","Encoded_Feature"]).reset_index(drop=True)

# --- Group back to original features: take best (lowest) rank among its columns ---
rfe_results['Original_Feature'] = rfe_results['Encoded_Feature'].str.split('=').str[0]
grouped = (rfe_results
           .groupby('Original_Feature', as_index=False)
           .agg(Best_Rank=('RFE_Rank','min'),
                Any_Selected=('Selected','max'),
                Columns=('Encoded_Feature','count'))
           .sort_values(['Best_Rank','Original_Feature'])
           .reset_index(drop=True))

print("\n=== RFE ranking (all encoded columns) ===")
print(rfe_results)

print("\n=== RFE grouped by original feature (best rank) ===")
print(grouped)

In [ ]:
! pip install boruta

In [ ]:
from boruta import BorutaPy
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

# Make a copy of X
X_boruta = X.copy()

# Convert categorical columns to numeric
for col in X_boruta.select_dtypes(include='category').columns:
    X_boruta[col] = LabelEncoder().fit_transform(X_boruta[col])

# Target should be numeric (if not already)
if y.dtype.name == "category" or y.dtype == object:
    y_boruta = LabelEncoder().fit_transform(y)
else:
    y_boruta = y.values

# RF for Boruta
rf = RandomForestClassifier(
    n_estimators=1000,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

boruta = BorutaPy(
    estimator=rf,
    n_estimators="auto",
    max_iter=200,
    random_state=42,
    verbose=0
)

# Fit Boruta
boruta.fit(X_boruta.values, y_boruta)

# Extract rankings and scores
boruta_rank = boruta.ranking_
max_boruta = boruta_rank.max()
boruta_score = max_boruta - boruta_rank + 1

# Build results DataFrame
boruta_results = pd.DataFrame({
    "Feature": X_boruta.columns,
    "Boruta_Rank": boruta_rank,
    "Boruta_Score": boruta_score
}).sort_values("Boruta_Rank").reset_index(drop=True)

print(boruta_results)

In [ ]:
# # Merge results
# merged = pd.merge(rfe_results[["Feature","RFE_Score"]],
#                   boruta_results[["Feature","Boruta_Score"]],
#                   on="Feature")

# # Min–max normalization
# for col in ["RFE_Score","Boruta_Score"]:
#     cmin, cmax = merged[col].min(), merged[col].max()
#     merged[col + "_Norm"] = (merged[col] - cmin) / (cmax - cmin) if cmax != cmin else 0

# # Average of normalized scores (MW)
# merged["MW"] = merged[["RFE_Score_Norm","Boruta_Score_Norm"]].mean(axis=1)

# # Sort by MW
# final_results = merged.sort_values("MW", ascending=False).reset_index(drop=True)

# print(final_results)

In [ ]:
# === ONE CELL to compute MF, ME, MW and merge ===
import numpy as np
import pandas as pd

from sklearn.feature_selection import chi2, f_classif, mutual_info_classif, RFE
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier

# ------- Split features / target -------
X = df.iloc[:, 0:16].copy()
y = df.iloc[:, -1].copy()

# ------------------ MF (Chi2, ANOVA F, MI/IG) ------------------
chi_scores, _ = chi2(X, y)
f_scores, _   = f_classif(X, y)
mi_scores     = mutual_info_classif(X, y, discrete_features=True, random_state=42)

mf_tbl = pd.DataFrame({
    "Feature": X.columns,
    "Chi2": chi_scores,
    "ANOVA_F": f_scores,
    "Mutual_Info": mi_scores,
    "Info_Gain": mi_scores,
})

# Min–max normalize each metric
for c in ["Chi2","ANOVA_F","Mutual_Info","Info_Gain"]:
    cmin, cmax = mf_tbl[c].min(), mf_tbl[c].max()
    mf_tbl[c + "_Norm"] = 0.0 if cmax == cmin else (mf_tbl[c] - cmin) / (cmax - cmin)

mf_tbl["MF"] = mf_tbl[["Chi2_Norm","ANOVA_F_Norm","Mutual_Info_Norm","Info_Gain_Norm"]].mean(axis=1)
final_results_MF = mf_tbl[["Feature","MF"]]

# ------------------ ME (Lasso + RandomForest) ------------------
lasso_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("logit", LogisticRegressionCV(
        Cs=np.logspace(-3, 3, 15),
        cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
        penalty="l1", solver="liblinear",
        scoring="f1_macro", max_iter=2000, n_jobs=-1, refit=True
    ))
])
lasso_clf.fit(X, y)

# Handle multi-class coefficients
coefs = np.abs(lasso_clf.named_steps["logit"].coef_)
if coefs.shape[0] > 1:  # multi-class
    lasso_coef = coefs.max(axis=0)
else:
    lasso_coef = coefs.ravel()

lasso_imp = pd.DataFrame({"Feature": X.columns, "Lasso_Importance": lasso_coef})

rf = RandomForestClassifier(n_estimators=500, class_weight="balanced", random_state=42, n_jobs=-1)
rf.fit(X, y)
rf_imp = pd.DataFrame({"Feature": X.columns, "RF_Importance": rf.feature_importances_})

me_tbl = lasso_imp.merge(rf_imp, on="Feature", how="inner")
for c in ["Lasso_Importance","RF_Importance"]:
    cmin, cmax = me_tbl[c].min(), me_tbl[c].max()
    me_tbl[c + "_Norm"] = 0.0 if cmax == cmin else (me_tbl[c] - cmin) / (cmax - cmin)
me_tbl["ME"] = me_tbl[["Lasso_Importance_Norm","RF_Importance_Norm"]].mean(axis=1)
final_results_ME = me_tbl[["Feature","ME"]]

# ------------------ MW (RFE + Boruta) ------------------
# RFE
base_est = LogisticRegression(solver="liblinear", class_weight="balanced", max_iter=2000, random_state=42)
rfe = RFE(estimator=base_est, n_features_to_select=8)
rfe.fit(X, y)
rfe_rank  = rfe.ranking_
rfe_score = rfe_rank.max() - rfe_rank + 1
rfe_tbl = pd.DataFrame({"Feature": X.columns, "RFE_Score": rfe_score})

# Boruta
boruta_ok = True
try:
    from boruta import BorutaPy
except Exception:
    try:
        from boruta_py import BorutaPy
    except Exception:
        boruta_ok = False

if boruta_ok:
    # Convert categorical columns to numeric if needed
    X_boruta = X.copy()
    for col in X_boruta.select_dtypes(include="category").columns:
        X_boruta[col] = LabelEncoder().fit_transform(X_boruta[col])

    y_boruta = y.copy()
    if y_boruta.dtype.name == "category" or y_boruta.dtype == object:
        y_boruta = LabelEncoder().fit_transform(y_boruta)

    rf_b = RandomForestClassifier(n_estimators=1000, class_weight="balanced",
                                  random_state=42, n_jobs=-1)
    boruta = BorutaPy(estimator=rf_b, n_estimators='auto', max_iter=200, random_state=42, verbose=0)
    boruta.fit(X_boruta.values, y_boruta)
    boruta_rank  = boruta.ranking_
    boruta_score = boruta_rank.max() - boruta_rank + 1
    boruta_tbl = pd.DataFrame({"Feature": X_boruta.columns, "Boruta_Score": boruta_score})
else:
    boruta_tbl = pd.DataFrame({"Feature": X.columns, "Boruta_Score": np.ones(X.shape[1])})

mw_tbl = rfe_tbl.merge(boruta_tbl, on="Feature", how="inner")
for c in ["RFE_Score","Boruta_Score"]:
    cmin, cmax = mw_tbl[c].min(), mw_tbl[c].max()
    mw_tbl[c + "_Norm"] = 0.0 if cmax == cmin else (mw_tbl[c] - cmin) / (cmax - cmin)
mw_tbl["MW"] = mw_tbl[["RFE_Score_Norm","Boruta_Score_Norm"]].mean(axis=1)
final_results_MW = mw_tbl[["Feature","MW"]]

# ------------------ Merge MF, ME, MW ------------------
all_scores = (
    final_results_MF
    .merge(final_results_ME, on="Feature", how="outer")
    .merge(final_results_MW, on="Feature", how="outer")
)

# Overall average & ranks
all_scores["Overall_Avg"]   = all_scores[["MF","ME","MW"]].mean(axis=1)
all_scores["Rank_Overall"]  = all_scores["Overall_Avg"].rank(ascending=False, method="dense").astype(int)

# Show
print(all_scores.sort_values("Overall_Avg", ascending=False).reset_index(drop=True))

In [ ]:
# Apply equal weights (0.33 each)
all_scores["MF_w"] = all_scores["MF"] * 0.33
all_scores["ME_w"] = all_scores["ME"] * 0.33
all_scores["MW_w"] = all_scores["MW"] * 0.33

# Weighted sum
all_scores["Weighted_Total"] = all_scores["MF_w"] + all_scores["ME_w"] + all_scores["MW_w"]

# Optional: rank by weighted total
all_scores["Rank_Weighted"] = all_scores["Weighted_Total"].rank(ascending=False, method="dense").astype(int)

# Final display
final_table = all_scores[["Feature","MF_w","ME_w","MW_w","Weighted_Total","Rank_Weighted"]].sort_values("Weighted_Total", ascending=False)

print(final_table)

In [ ]:
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier, AdaBoostClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.svm import SVC
# from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, roc_curve, auc
# import matplotlib.pyplot as plt
# import numpy as np

# # ===========================
# # Step 0: feature weights source (MF/ME/MW or avg_table)
# # ===========================
# feature_weights_sources = {}
# if 'all_scores' in globals():
#     fw = all_scores[['Feature','MF','ME','MW']].set_index('Feature')
#     feature_weights_sources['MF'] = fw['MF'].to_dict()
#     feature_weights_sources['ME'] = fw['ME'].to_dict()
#     feature_weights_sources['MW'] = fw['MW'].to_dict()
# elif 'avg_table' in globals():
#     fw = avg_table.set_index('Feature')
#     feature_weights_sources['MF'] = fw['Filter Avg (Norm)'].to_dict()
#     feature_weights_sources['ME'] = fw['Embedded Avg (Norm)'].to_dict()
#     feature_weights_sources['MW'] = fw['Wrapper Avg (Norm)'].to_dict()
# else:
#     raise ValueError("Provide all_scores with MF/ME/MW or avg_table with Filter/Embedded/Wrapper Avg (Norm).")

# # ===========================
# # Step 1: Classifiers
# # ===========================
# classifiers = {
#     "RandomForest": RandomForestClassifier(random_state=42),
#     "LogisticRegression": LogisticRegression(max_iter=1000, random_state=42),
#     "ExtraTrees": ExtraTreesClassifier(random_state=42),
#     "GradientBoost": GradientBoostingClassifier(random_state=42),
#     "SVM": SVC(probability=True, random_state=42),
#     "AdaBoost": AdaBoostClassifier(random_state=42)
# }

# score_cols = ["MF", "ME", "MW"]
# results = []

# # ===========================
# # Step 2: Train & Evaluate
# # ===========================
# for score in score_cols:
#     weights = feature_weights_sources[score]
#     X_weighted = X.copy()
#     for col in X_weighted.columns:
#         X_weighted[col] = X_weighted[col] * float(weights.get(col, 1.0))

#     X_train, X_test, y_train, y_test = train_test_split(
#         X_weighted, y, test_size=0.2, random_state=42, stratify=y
#     )

#     is_binary = (y_train.nunique() == 2)

#     for clf_name, clf in classifiers.items():
#         clf.fit(X_train, y_train)
#         y_pred = clf.predict(X_test)

#         acc = accuracy_score(y_test, y_pred)
#         f1  = f1_score(y_test, y_pred, average="weighted")

#         auc_score = None
#         y_prob = None
#         if hasattr(clf, "predict_proba"):
#             proba = clf.predict_proba(X_test)
#             if is_binary:
#                 y_prob = proba[:, 1]
#                 auc_score = roc_auc_score(y_test, y_prob)
#             else:
#                 auc_score = roc_auc_score(y_test, proba, multi_class='ovr', average='weighted')
#         elif hasattr(clf, "decision_function"):
#             scores = clf.decision_function(X_test)
#             if is_binary:
#                 y_prob = scores
#                 auc_score = roc_auc_score(y_test, y_prob)
#             else:
#                 auc_score = roc_auc_score(y_test, scores, multi_class='ovr', average='weighted')

#         results.append({
#             "Feature Source": score,
#             "Classifier": clf_name,
#             "Accuracy": acc,
#             "F1 Score": f1,
#             "AUC": auc_score
#         })

#         if is_binary and y_prob is not None:
#             fpr, tpr, _ = roc_curve(y_test, y_prob)
#             roc_auc = auc(fpr, tpr)
#             plt.figure()
#             plt.plot(fpr, tpr, label=f"{clf_name} (AUC = {roc_auc:.2f})")
#             plt.plot([0, 1], [0, 1], linestyle="--", color="gray")
#             plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
#             plt.title(f"ROC Curve - {clf_name} ({score})")
#             plt.legend(loc="lower right")
#             plt.show()

# results_df = pd.DataFrame(results)
# display(results_df.pivot(index="Classifier", columns="Feature Source", values=["Accuracy","F1 Score","AUC"]))

##FEATURE ELIMINATION

In [ ]:
import pandas as pd
import itertools

# --- Prepare scores table safely ---
if 'avg_table' in globals():
    df = avg_table.rename(columns={
        "Filter Avg (Norm)": "MG",
        "Embedded Avg (Norm)": "ME",
        "Wrapper Avg (Norm)": "MW"
    }).reset_index(drop=True)
    df = df[["Feature","MG","ME","MW"]].copy()

elif 'all_scores' in globals():
    df = all_scores.rename(columns={
        "MF": "MG",
        "ME": "ME",
        "MW": "MW"
    }).reset_index(drop=True)
    df = df[["Feature","MG","ME","MW"]].copy()
else:
    raise ValueError("Neither avg_table nor all_scores is defined!")

# --- All ordered feature pairs ---
pairs = list(itertools.product(df["Feature"], df["Feature"]))
results = []

for a, b in pairs:
    a_vals = df.loc[df["Feature"] == a, ["MG", "ME", "MW"]].values[0]
    b_vals = df.loc[df["Feature"] == b, ["MG", "ME", "MW"]].values[0]

    mg_check = "✓" if a_vals[0] >= b_vals[0] else "✗"
    me_check = "✓" if a_vals[1] >= b_vals[1] else "✗"
    mw_check = "✓" if a_vals[2] >= b_vals[2] else "✗"

    wins = sum([mg_check=="✓", me_check=="✓", mw_check=="✓"])
    c_ab = wins / 3
    decision = "Yes" if c_ab >= 0.6599 else "No"

    results.append([a, b, mg_check, me_check, mw_check, wins, round(c_ab, 4), decision])

comparison_table = pd.DataFrame(results,
    columns=["A", "B", "MG", "ME", "MW", "Wins", "C(a,b)", "Decision"])

# --- Eliminate features that always lose ---
eliminate_features = [
    feature for feature in df["Feature"]
    if all(
        comparison_table[(comparison_table["A"] == feature) & (comparison_table["A"] != comparison_table["B"])]["Decision"] == "No"
    )
]

filtered_df = df[~df["Feature"].isin(eliminate_features)]

# --- Show results ---
print("Original DataFrame:\n", df)
print("\nFeatures to eliminate:", eliminate_features)
print("\nFiltered DataFrame:\n", filtered_df)

## ENTRY FLOW AND LEAVING FLOW SUM FEATURE WISE AND PHI Calculation (feature wise)

In [ ]:
import pandas as pd
import itertools

# Step 0: Prepare MG/ME/MW from all_scores
df = all_scores.rename(columns={
    "MF": "MG",
    "ME": "ME",
    "MW": "MW"
})[["Feature","MG","ME","MW"]].reset_index(drop=True)

# Step 1: Build comparison table to find eliminated features
pairs = list(itertools.product(df["Feature"], df["Feature"]))
results = []

for a, b in pairs:
    a_vals = df.loc[df["Feature"] == a, ["MG", "ME", "MW"]].values[0]
    b_vals = df.loc[df["Feature"] == b, ["MG", "ME", "MW"]].values[0]

    mg_check = "✓" if a_vals[0] >= b_vals[0] else "✗"
    me_check = "✓" if a_vals[1] >= b_vals[1] else "✗"
    mw_check = "✓" if a_vals[2] >= b_vals[2] else "✗"

    wins = sum([mg_check=="✓", me_check=="✓", mw_check=="✓"])
    c_ab = wins / 3
    decision = "Yes" if c_ab >= 0.6599 else "No"

    results.append([a, b, mg_check, me_check, mw_check, wins, round(c_ab, 4), decision])

comparison_table = pd.DataFrame(
    results, columns=["A", "B", "MG", "ME", "MW", "Wins", "C(a,b)", "Decision"]
)

# Step 2: Get only remaining features
eliminate_features = [
    feature for feature in df["Feature"]
    if all(
        comparison_table[(comparison_table["A"] == feature) &
                         (comparison_table["A"] != comparison_table["B"])]["Decision"] == "No"
    )
]

filtered_df = df[~df["Feature"].isin(eliminate_features)].reset_index(drop=True)

# Step 3: Compute pi(a,b) for all pairs (a != b) with debug
pi_results = []

for entry in filtered_df["Feature"]:
    entry_vals = filtered_df.loc[filtered_df["Feature"] == entry, ["MG", "ME", "MW"]].values[0]

    for leaving in filtered_df["Feature"]:
        if entry == leaving:
            continue

        leaving_vals = filtered_df.loc[filtered_df["Feature"] == leaving, ["MG", "ME", "MW"]].values[0]

        # Direct differences (can be negative)
        mg_diff = entry_vals[0] - leaving_vals[0]
        me_diff = entry_vals[1] - leaving_vals[1]
        mw_diff = entry_vals[2] - leaving_vals[2]

        pi_val = round((mg_diff + me_diff + mw_diff) / 3, 4)

        # Debug string
        calc_str = f"(({entry_vals[0]}-{leaving_vals[0]}) + ({entry_vals[1]}-{leaving_vals[1]}) + ({entry_vals[2]}-{leaving_vals[2]})) / 3 = {pi_val}"

        pi_results.append({
            "Entry Flow": entry,
            "Leaving Flow": leaving,
            "MG_diff": round(mg_diff, 4),
            "ME_diff": round(me_diff, 4),
            "MW_diff": round(mw_diff, 4),
            "pi": pi_val,
            "Calculation": calc_str
        })

pi_df = pd.DataFrame(pi_results)

# Step 4: Compute phi+ and phi- for each feature
phi_plus = pi_df.groupby("Entry Flow")["pi"].mean().rename("phi+")
phi_minus = pi_df.groupby("Leaving Flow")["pi"].mean().rename("phi-")

phi_table = pd.concat([phi_plus, phi_minus], axis=1).reset_index().rename(columns={"index":"Feature"})

# Step 5: Compute Net Flow (phi = phi+ - phi-)
phi_table["phi"] = (phi_table["phi+"] - phi_table["phi-"]).round(4)

# Step 6: Rank features by Net Flow (descending)
phi_table["Rank"] = phi_table["phi"].rank(method="dense", ascending=False).astype(int)

print("\nPairwise Preference Index (pi with full calculation):\n")
print(pi_df.to_string(index=False))

print("\nPhi+ , Phi- , Net Flow (phi) and Ranking:\n")
print(phi_table.sort_values("Rank").to_string(index=False))

## THIS IS MULTIPILER Value feature wise

In [ ]:
# Step 1: Compute phi + 1 and store in 'multiplier'
phi_table["multiplier"] = (phi_table["phi"] + 1).round(4)

# Step 2: Prepare final_scores table
final_scores = phi_table[["Feature", "multiplier"]].rename(columns={"multiplier": "phi"})

# Step 3: Display results
print("Final scores with multiplier (phi + 1):\n")
print(final_scores.to_string(index=False))

## This is the feature wise very first "IG SKB RFE" value

In [ ]:
import pandas as pd

filtered_copy = filtered_df.copy()



# Step 1: Merge filtered_copy with final_scores to get multiplier for each feature
merged = filtered_copy.merge(final_scores, on="Feature", how="left")

# Step 2: Multiply MG, ME, MW by multiplier
merged["MG_phi"] = (merged["MG"] * merged["phi"]).round(4)
merged["ME_phi"] = (merged["ME"] * merged["phi"]).round(4)
merged["MW_phi"] = (merged["MW"] * merged["phi"]).round(4)

# Step 3: Final table with original MG/ME/MW and multiplied values
phi_table_final = merged[["Feature", "MG", "ME", "MW", "phi", "MG_phi", "ME_phi", "MW_phi"]]

print("\nFinal Table with feature-wise multiplier applied:\n")
print(phi_table_final.to_string(index=False))

In [ ]:
# Step 3: Cap values at 1
merged["MG_phi_capped"] = merged["MG_phi"].apply(lambda x: min(x, 1))
merged["ME_phi_capped"] = merged["ME_phi"].apply(lambda x: min(x, 1))
merged["MW_phi_capped"] = merged["MW_phi"].apply(lambda x: min(x, 1))

# Step 4: Final table with original, multiplied and capped values
phi_table_final = merged[[
    "Feature", "MG", "ME", "MW", "phi",
    "MG_phi", "ME_phi", "MW_phi",
    "MG_phi_capped", "ME_phi_capped", "MW_phi_capped"
]]

print("\nFinal Table with feature-wise multiplier applied and capped at 1:\n")
print(phi_table_final.to_string(index=False))

In [ ]:
# Step 5: Multiply capped values by 1/3
merged["MG_final"] = (merged["MG_phi_capped"] * (1/3)).round(4)
merged["ME_final"] = (merged["ME_phi_capped"] * (1/3)).round(4)
merged["MW_final"] = (merged["MW_phi_capped"] * (1/3)).round(4)

# Step 6: Final weighted table with only required columns
final_weighted_table = merged[["Feature", "MG_final", "ME_final", "MW_final"]]

print("\nFinal Weighted Table (capped values × 1/3):\n")
print(final_weighted_table.to_string(index=False))

In [ ]:
# import pandas as pd

# # new_feature_values has: ["Feature", "MG_new", "ME_new", "MW_new", ...]
# # 1) pick the criteria columns (everything except 'Feature', or only *_new)
# crit_cols = [c for c in new_feature_values.columns if c != "Feature"]
# # Or, if you prefer only the clamped columns:
# # crit_cols = [c for c in new_feature_values.columns if c.endswith("_new")]

# # 2) number of criteria (j)
# j = len(crit_cols)

# # 3) SPOTIS distances with aspiration = 1 for all criteria
# spotis = new_feature_values[crit_cols].rsub(1.0).abs().sum(axis=1) / j

# # 4) attach & rank (lower is better)
# result = new_feature_values.copy()
# result["SPOTIS_Distance"] = spotis
# result_sorted = result.sort_values("SPOTIS_Distance", ascending=True)

# print("SPOTIS distances (lower = better):")
# print(result_sorted[["Feature", "SPOTIS_Distance"]])

In [ ]:
# Column-wise Max (Ideal Best) এবং Min (Ideal Worst)
A_plus = final_weighted_table[["MG_final", "ME_final", "MW_final"]].max().rename("A+ (Ideal Best)")
A_minus = final_weighted_table[["MG_final", "ME_final", "MW_final"]].min().rename("A- (Ideal Worst)")

# Column-wise Mean
mean_values = final_weighted_table[["MG_final", "ME_final", "MW_final"]].mean().rename("Mean")

# একসাথে DataFrame হিসেবে দেখানো
ideal_df = pd.concat([A_plus, A_minus, mean_values], axis=1)

print("Ideal Best (A+), Ideal Worst (A-) and Mean values per column:\n")
print(ideal_df)

## IDEAL BEST AND WORST VALUE MG ME MW WISE

In [ ]:
import numpy as np

# Step 1: Column-wise mean (from previous calculation)
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

print(f"Column Means:\nMG_mean={mg_mean}, ME_mean={me_mean}, MW_mean={mw_mean}\n")

# Step 2: Calculate squared differences from mean for each feature
mg_sq_diff = (final_weighted_table["MG_final"] - mg_mean)**2
me_sq_diff = (final_weighted_table["ME_final"] - me_mean)**2
mw_sq_diff = (final_weighted_table["MW_final"] - mw_mean)**2

print("Squared differences per feature:")
print(pd.DataFrame({
    "Feature": final_weighted_table["Feature"],
    "MG_sq_diff": mg_sq_diff,
    "ME_sq_diff": me_sq_diff,
    "MW_sq_diff": mw_sq_diff
}))

# Step 3: Compute variance (mean of squared differences)
mg_var = mg_sq_diff.mean()
me_var = me_sq_diff.mean()
mw_var = mw_sq_diff.mean()

print(f"\nColumn Variances:\nMG_var={mg_var}, ME_var={me_var}, MW_var={mw_var}")

# Step 4: Standard Deviation = sqrt(variance)
mg_sd = np.sqrt(mg_var)
me_sd = np.sqrt(me_var)
mw_sd = np.sqrt(mw_var)

print(f"\nColumn Standard Deviations (SD):\nMG_SD={mg_sd}, ME_SD={me_sd}, MW_SD={mw_sd}")

In [ ]:
# Step 5: Multiply capped values by 1/3
merged["MG_final"] = (merged["MG_phi_capped"] * (1/3)).round(4)
merged["ME_final"] = (merged["ME_phi_capped"] * (1/3)).round(4)
merged["MW_final"] = (merged["MW_phi_capped"] * (1/3)).round(4)

# Step 6: Final weighted table with only required columns
final_weighted_table = merged[["Feature", "MG_final", "ME_final", "MW_final"]]

print("\nFinal Weighted Table (capped values × 1/3):\n")
print(final_weighted_table.to_string(index=False))

# --- Step 7: A+ (Ideal Best) from final_weighted_table ---
A_plus = final_weighted_table[["MG_final", "ME_final", "MW_final"]].max().rename("A+ (Ideal Best)")
print("\nA+ (Ideal Best) values:\n")
print(A_plus)

# --- Step 8: Absolute Difference |Feature - A+| per feature ---
diff_results = []
for _, row in final_weighted_table.iterrows():
    diff_results.append({
        "Feature": row["Feature"],
        "MG_value": row["MG_final"],
        "ME_value": row["ME_final"],
        "MW_value": row["MW_final"],
        "MG_d+": abs(row["MG_final"] - A_plus["MG_final"]),
        "ME_d+": abs(row["ME_final"] - A_plus["ME_final"]),
        "MW_d+": abs(row["MW_final"] - A_plus["MW_final"])
    })

diff_df_final = pd.DataFrame(diff_results)

print("\nFeature values with Absolute Difference |Feature - A+| (MG/ME/MW):\n")
print(diff_df_final.to_string(index=False))

In [ ]:
# Step 5: Multiply capped values by 1/3
merged["MG_final"] = (merged["MG_phi_capped"] * (1/3)).round(4)
merged["ME_final"] = (merged["ME_phi_capped"] * (1/3)).round(4)
merged["MW_final"] = (merged["MW_phi_capped"] * (1/3)).round(4)

# Step 6: Final weighted table with only required columns
final_weighted_table = merged[["Feature", "MG_final", "ME_final", "MW_final"]]

print("\nFinal Weighted Table (capped values × 1/3):\n")
print(final_weighted_table.to_string(index=False))

# --- Step 7: A- (Ideal Worst) from final_weighted_table ---
A_minus = final_weighted_table[["MG_final", "ME_final", "MW_final"]].min().rename("A- (Ideal Worst)")
print("\nA- (Ideal Worst) values:\n")
print(A_minus)

# --- Step 8: Absolute Difference |Feature - A-| per feature ---
diff_results = []
for _, row in final_weighted_table.iterrows():
    diff_results.append({
        "Feature": row["Feature"],
        "MG_value": row["MG_final"],
        "ME_value": row["ME_final"],
        "MW_value": row["MW_final"],
        "MG_d-": abs(row["MG_final"] - A_minus["MG_final"]),
        "ME_d-": abs(row["ME_final"] - A_minus["ME_final"]),
        "MW_d-": abs(row["MW_final"] - A_minus["MW_final"])
    })

diff_df_worst = pd.DataFrame(diff_results)

print("\nFeature values with Absolute Difference |Feature - A-| (MG/ME/MW):\n")
print(diff_df_worst.to_string(index=False))

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

# --- Step 2: Squared differences from mean ---
mg_sq_diff = (final_weighted_table["MG_final"] - mg_mean) ** 2
me_sq_diff = (final_weighted_table["ME_final"] - me_mean) ** 2
mw_sq_diff = (final_weighted_table["MW_final"] - mw_mean) ** 2

# --- Step 3: Variances ---
mg_var = mg_sq_diff.mean()
me_var = me_sq_diff.mean()
mw_var = mw_sq_diff.mean()

# --- Step 4: Standard Deviations ---
mg_sd = np.sqrt(mg_var)
me_sd = np.sqrt(me_var)
mw_sd = np.sqrt(mw_var)

print("\nColumn Standard Deviations (SD):")
print(f"MG_SD={mg_sd}, ME_SD={me_sd}, MW_SD={mw_sd}")

# --- Step 5: Ideal Best (A+) ---
A_plus = final_weighted_table[["MG_final", "ME_final", "MW_final"]].max().rename("A+ (Ideal Best)")
print("\nA+ (Ideal Best):")
print(A_plus)

# --- Step 6: Absolute Distance ---
diff_results = []
for _, row in final_weighted_table.iterrows():
    diff_results.append({
        "Feature": row["Feature"],
        "MG_abs": abs(row["MG_final"] - A_plus["MG_final"]),
        "ME_abs": abs(row["ME_final"] - A_plus["ME_final"]),
        "MW_abs": abs(row["MW_final"] - A_plus["MW_final"])
    })

diff_df = pd.DataFrame(diff_results)

# --- Step 7: Scaled Difference (abs / SD) ---
diff_df["MG_scaled"] = diff_df["MG_abs"] / mg_sd if mg_sd != 0 else 0
diff_df["ME_scaled"] = diff_df["ME_abs"] / me_sd if me_sd != 0 else 0
diff_df["MW_scaled"] = diff_df["MW_abs"] / mw_sd if mw_sd != 0 else 0

print("\nAbsolute Distance and Scaled Difference (per feature):")
print(diff_df.to_string(index=False))

# --- Step 8: Distance Calculations ---
# Manhattan distance = sum of scaled differences per feature
diff_df["Manhattan"] = diff_df[["MG_scaled", "ME_scaled", "MW_scaled"]].sum(axis=1)

# Euclidean distance = sqrt of sum of squares of scaled differences per feature
diff_df["Euclidean"] = np.sqrt((diff_df[["MG_scaled", "ME_scaled", "MW_scaled"]] ** 2).sum(axis=1))

# Chebyshev distance = max of scaled differences per feature
diff_df["Chebyshev"] = diff_df[["MG_scaled", "ME_scaled", "MW_scaled"]].max(axis=1)

print("\nDistance Metrics (per feature):")
print(diff_df[["Feature", "Manhattan", "Euclidean", "Chebyshev"]].to_string(index=False))



# --- Step 9: Log-based D+ calculation ---
diff_df["D_plus"] = (
    (np.log10(1 + diff_df["Manhattan"]))**2 +
    (np.log10(1 + diff_df["Euclidean"]))**2 +
    (np.log10(1 + diff_df["Chebyshev"]))**2
)

# --- Final Output ---
print("\nDistance Metrics with D+ (per feature):")
print(diff_df[["Feature","Manhattan","Euclidean","Chebyshev","D_plus"]].to_string(index=False))

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

# --- Step 2: Squared differences from mean ---
mg_sq_diff = (final_weighted_table["MG_final"] - mg_mean)**2
me_sq_diff = (final_weighted_table["ME_final"] - me_mean)**2
mw_sq_diff = (final_weighted_table["MW_final"] - mw_mean)**2

# --- Step 3: Variances ---
mg_var = mg_sq_diff.mean()
me_var = me_sq_diff.mean()
mw_var = mw_sq_diff.mean()

# --- Step 4: Standard Deviations ---
mg_sd = np.sqrt(mg_var)
me_sd = np.sqrt(me_var)
mw_sd = np.sqrt(mw_var)

print("\nColumn Standard Deviations (SD):")
print(f"MG_SD={mg_sd}, ME_SD={me_sd}, MW_SD={mw_sd}")

# --- Step 5: Ideal Worst (A-) ---
A_minus = final_weighted_table[["MG_final","ME_final","MW_final"]].min().rename("A- (Ideal Worst)")
print("\nA- (Ideal Worst):")
print(A_minus)

# --- Step 6: Absolute Distance from A- ---
diff_results = []
for _, row in final_weighted_table.iterrows():
    diff_results.append({
        "Feature": row["Feature"],
        "MG_abs": abs(row["MG_final"] - A_minus["MG_final"]),
        "ME_abs": abs(row["ME_final"] - A_minus["ME_final"]),
        "MW_abs": abs(row["MW_final"] - A_minus["MW_final"])
    })

diff_df = pd.DataFrame(diff_results)

# --- Step 7: Scaled Difference using SD ---
diff_df["MG_scaled"] = diff_df["MG_abs"] / mg_sd if mg_sd != 0 else 0
diff_df["ME_scaled"] = diff_df["ME_abs"] / me_sd if me_sd != 0 else 0
diff_df["MW_scaled"] = diff_df["MW_abs"] / mw_sd if mw_sd != 0 else 0

print("\nAbsolute Distance and Scaled Difference (per feature, using A-):")
print(diff_df.to_string(index=False))
# --- Step 8: Distance Calculations ---

# Manhattan distance = sum of scaled differences per feature
diff_df["Manhattan"] = diff_df[["MG_scaled","ME_scaled","MW_scaled"]].sum(axis=1)

# Euclidean distance = sqrt of sum of squares of scaled differences per feature
diff_df["Euclidean"] = np.sqrt((diff_df[["MG_scaled","ME_scaled","MW_scaled"]]**2).sum(axis=1))

# Chebyshev distance = max of scaled differences per feature
diff_df["Chebyshev"] = diff_df[["MG_scaled","ME_scaled","MW_scaled"]].max(axis=1)

print("\nDistance Metrics (per feature):")
print(diff_df[["Feature","Manhattan","Euclidean","Chebyshev"]].to_string(index=False))


# --- Step 9: Log-based D- calculation ---
diff_df["D_minus"] = (
    (np.log10(1 + diff_df["Manhattan"]))**2 +
    (np.log10(1 + diff_df["Euclidean"]))**2 +
    (np.log10(1 + diff_df["Chebyshev"]))**2
)

# --- Final Output ---
print("\nDistance Metrics with D- (per feature):")
print(diff_df[["Feature","Manhattan","Euclidean","Chebyshev","D_minus"]].to_string(index=False))

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

mg_sq_diff = (final_weighted_table["MG_final"] - mg_mean)**2
me_sq_diff = (final_weighted_table["ME_final"] - me_mean)**2
mw_sq_diff = (final_weighted_table["MW_final"] - mw_mean)**2

mg_sd = np.sqrt(mg_sq_diff.mean())
me_sd = np.sqrt(me_sq_diff.mean())
mw_sd = np.sqrt(mw_sq_diff.mean())

# --- Step 2: Ideal Best (A+) and Ideal Worst (A-) ---
A_plus = final_weighted_table[["MG_final","ME_final","MW_final"]].max()
A_minus = final_weighted_table[["MG_final","ME_final","MW_final"]].min()

# --- Step 3: Distances from A+ (D+) ---
diff_plus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_plus["MG_final"]) / (mg_sd if mg_sd!=0 else 1)
    ME_abs = abs(row["ME_final"] - A_plus["ME_final"]) / (me_sd if me_sd!=0 else 1)
    MW_abs = abs(row["MW_final"] - A_plus["MW_final"]) / (mw_sd if mw_sd!=0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_plus = (np.log10(1+M))**2 + (np.log10(1+E))**2 + (np.log10(1+H))**2
    diff_plus.append({"Feature": row["Feature"], "D_plus": D_plus})

diff_df_plus = pd.DataFrame(diff_plus)

# --- Step 4: Distances from A- (D-) ---
diff_minus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_minus["MG_final"]) / (mg_sd if mg_sd!=0 else 1)
    ME_abs = abs(row["ME_final"] - A_minus["ME_final"]) / (me_sd if me_sd!=0 else 1)
    MW_abs = abs(row["MW_final"] - A_minus["MW_final"]) / (mw_sd if mw_sd!=0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_minus = (np.log10(1+M))**2 + (np.log10(1+E))**2 + (np.log10(1+H))**2
    diff_minus.append({"Feature": row["Feature"], "D_minus": D_minus})

diff_df_minus = pd.DataFrame(diff_minus)

# --- Step 5: Merge and compute PC + OC + Final Score ---
pc_df = diff_df_plus.merge(diff_df_minus, on="Feature", how="inner")

pc_df["PC"] = pc_df["D_minus"] / (pc_df["D_plus"] + pc_df["D_minus"])
pc_df["OC"] = 1 / (1 + pc_df["D_plus"])
pc_df["Score"] = 0.5 * pc_df["PC"] + 0.5 * pc_df["OC"]   # <-- NEW COMBINED SCORE
pc_df["Rank"] = pc_df["Score"].rank(ascending=False, method="dense").astype(int)

print("\nPC, OC, and Combined Score per feature:")
print(pc_df[["Feature","D_plus","D_minus","PC","OC","Score","Rank"]].to_string(index=False))

## D+ calculation using sqrt of logarithmic

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

# --- Step 2: Squared differences from mean ---
mg_sq_diff = (final_weighted_table["MG_final"] - mg_mean) ** 2
me_sq_diff = (final_weighted_table["ME_final"] - me_mean) ** 2
mw_sq_diff = (final_weighted_table["MW_final"] - mw_mean) ** 2

# --- Step 3: Variances ---
mg_var = mg_sq_diff.mean()
me_var = me_sq_diff.mean()
mw_var = mw_sq_diff.mean()

# --- Step 4: Standard Deviations ---
mg_sd = np.sqrt(mg_var)
me_sd = np.sqrt(me_var)
mw_sd = np.sqrt(mw_var)

print("\nColumn Standard Deviations (SD):")
print(f"MG_SD={mg_sd}, ME_SD={me_sd}, MW_SD={mw_sd}")

# --- Step 5: Ideal Best (A+) ---
A_plus = final_weighted_table[["MG_final", "ME_final", "MW_final"]].max().rename("A+ (Ideal Best)")
print("\nA+ (Ideal Best):")
print(A_plus)

# --- Step 6: Absolute Distance ---
diff_results = []
for _, row in final_weighted_table.iterrows():
    diff_results.append({
        "Feature": row["Feature"],
        "MG_abs": abs(row["MG_final"] - A_plus["MG_final"]),
        "ME_abs": abs(row["ME_final"] - A_plus["ME_final"]),
        "MW_abs": abs(row["MW_final"] - A_plus["MW_final"])
    })

diff_df = pd.DataFrame(diff_results)

# --- Step 7: Scaled Difference (abs / SD) ---
diff_df["MG_scaled"] = diff_df["MG_abs"] / mg_sd if mg_sd != 0 else 0
diff_df["ME_scaled"] = diff_df["ME_abs"] / me_sd if me_sd != 0 else 0
diff_df["MW_scaled"] = diff_df["MW_abs"] / mw_sd if mw_sd != 0 else 0

print("\nAbsolute Distance and Scaled Difference (per feature):")
print(diff_df.to_string(index=False))

# --- Step 8: Distance Calculations ---
# Manhattan distance = sum of scaled differences per feature
diff_df["Manhattan"] = diff_df[["MG_scaled", "ME_scaled", "MW_scaled"]].sum(axis=1)

# Euclidean distance = sqrt of sum of squares of scaled differences per feature
diff_df["Euclidean"] = np.sqrt((diff_df[["MG_scaled", "ME_scaled", "MW_scaled"]] ** 2).sum(axis=1))

# Chebyshev distance = max of scaled differences per feature
diff_df["Chebyshev"] = diff_df[["MG_scaled", "ME_scaled", "MW_scaled"]].max(axis=1)

print("\nDistance Metrics (per feature):")
print(diff_df[["Feature", "Manhattan", "Euclidean", "Chebyshev"]].to_string(index=False))



# --- Step 9: Log-based D+ calculation with extra root ---
diff_df["D_plus(sqrt)"] = np.sqrt(
    (np.log10(1 + diff_df["Manhattan"]))**2 +
    (np.log10(1 + diff_df["Euclidean"]))**2 +
    (np.log10(1 + diff_df["Chebyshev"]))**2
)

# --- Final Output ---
print("\nDistance Metrics with D+ (per feature):")
print(diff_df[["Feature","Manhattan","Euclidean","Chebyshev","D_plus(sqrt)"]].to_string(index=False))

## D- using sqrt log

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

# --- Step 2: Squared differences from mean ---
mg_sq_diff = (final_weighted_table["MG_final"] - mg_mean)**2
me_sq_diff = (final_weighted_table["ME_final"] - me_mean)**2
mw_sq_diff = (final_weighted_table["MW_final"] - mw_mean)**2

# --- Step 3: Variances ---
mg_var = mg_sq_diff.mean()
me_var = me_sq_diff.mean()
mw_var = mw_sq_diff.mean()

# --- Step 4: Standard Deviations ---
mg_sd = np.sqrt(mg_var)
me_sd = np.sqrt(me_var)
mw_sd = np.sqrt(mw_var)

print("\nColumn Standard Deviations (SD):")
print(f"MG_SD={mg_sd}, ME_SD={me_sd}, MW_SD={mw_sd}")

# --- Step 5: Ideal Worst (A-) ---
A_minus = final_weighted_table[["MG_final","ME_final","MW_final"]].min().rename("A- (Ideal Worst)")
print("\nA- (Ideal Worst):")
print(A_minus)

# --- Step 6: Absolute Distance from A- ---
diff_results = []
for _, row in final_weighted_table.iterrows():
    diff_results.append({
        "Feature": row["Feature"],
        "MG_abs": abs(row["MG_final"] - A_minus["MG_final"]),
        "ME_abs": abs(row["ME_final"] - A_minus["ME_final"]),
        "MW_abs": abs(row["MW_final"] - A_minus["MW_final"])
    })

diff_df = pd.DataFrame(diff_results)

# --- Step 7: Scaled Difference using SD ---
diff_df["MG_scaled"] = diff_df["MG_abs"] / mg_sd if mg_sd != 0 else 0
diff_df["ME_scaled"] = diff_df["ME_abs"] / me_sd if me_sd != 0 else 0
diff_df["MW_scaled"] = diff_df["MW_abs"] / mw_sd if mw_sd != 0 else 0

print("\nAbsolute Distance and Scaled Difference (per feature, using A-):")
print(diff_df.to_string(index=False))
# --- Step 8: Distance Calculations ---

# Manhattan distance = sum of scaled differences per feature
diff_df["Manhattan"] = diff_df[["MG_scaled","ME_scaled","MW_scaled"]].sum(axis=1)

# Euclidean distance = sqrt of sum of squares of scaled differences per feature
diff_df["Euclidean"] = np.sqrt((diff_df[["MG_scaled","ME_scaled","MW_scaled"]]**2).sum(axis=1))

# Chebyshev distance = max of scaled differences per feature
diff_df["Chebyshev"] = diff_df[["MG_scaled","ME_scaled","MW_scaled"]].max(axis=1)

print("\nDistance Metrics (per feature):")
print(diff_df[["Feature","Manhattan","Euclidean","Chebyshev"]].to_string(index=False))


# --- Step 9: Log-based D- calculation ---
diff_df["D_minus(sqrt)"] = np.sqrt(
    (np.log10(1 + diff_df["Manhattan"]))**2 +
    (np.log10(1 + diff_df["Euclidean"]))**2 +
    (np.log10(1 + diff_df["Chebyshev"]))**2
)

# --- Final Output ---
print("\nDistance Metrics with D- (per feature):")
print(diff_df[["Feature","Manhattan","Euclidean","Chebyshev","D_minus(sqrt)"]].to_string(index=False))

## S calculation using sqrt log

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean & SD ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

mg_sq_diff = (final_weighted_table["MG_final"] - mg_mean) ** 2
me_sq_diff = (final_weighted_table["ME_final"] - me_mean) ** 2
mw_sq_diff = (final_weighted_table["MW_final"] - mw_mean) ** 2

mg_sd = np.sqrt(mg_sq_diff.mean())
me_sd = np.sqrt(me_sq_diff.mean())
mw_sd = np.sqrt(mw_sq_diff.mean())

# --- Step 2: Ideal Best (A+) and Ideal Worst (A-) ---
A_plus = final_weighted_table[["MG_final", "ME_final", "MW_final"]].max()
A_minus = final_weighted_table[["MG_final", "ME_final", "MW_final"]].min()

# --- Step 3: Distances from A+ (D_plus(sqrt)) ---
diff_plus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_plus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_plus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_plus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_plus_sqrt = np.sqrt(
        (np.log10(1 + M))**2 +
        (np.log10(1 + E))**2 +
        (np.log10(1 + H))**2
    )

    diff_plus.append({"Feature": row["Feature"], "D_plus(sqrt)": D_plus_sqrt})

diff_df_plus = pd.DataFrame(diff_plus)

# --- Step 4: Distances from A- (D_minus(sqrt)) ---
diff_minus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_minus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_minus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_minus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_minus_sqrt = np.sqrt(
        (np.log10(1 + M))**2 +
        (np.log10(1 + E))**2 +
        (np.log10(1 + H))**2
    )

    diff_minus.append({"Feature": row["Feature"], "D_minus(sqrt)": D_minus_sqrt})

diff_df_minus = pd.DataFrame(diff_minus)

# --- Step 5: Merge and compute PC + OC + Final Score ---
pc_df = diff_df_plus.merge(diff_df_minus, on="Feature", how="inner")

pc_df["PC"] = pc_df["D_minus(sqrt)"] / (pc_df["D_plus(sqrt)"] + pc_df["D_minus(sqrt)"])
pc_df["OC"] = 1 / (1 + pc_df["D_plus(sqrt)"])
pc_df["Score"] = 0.5 * pc_df["PC"] + 0.5 * pc_df["OC"]
pc_df["Rank"] = pc_df["Score"].rank(ascending=False, method="dense").astype(int)

print("\nPC, OC, and Combined Score per feature:")
print(pc_df[["Feature", "D_plus(sqrt)", "D_minus(sqrt)", "PC", "OC", "Score", "Rank"]].to_string(index=False))

## root(M)+root(E)+root(H)

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean & SD ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

mg_sq_diff = (final_weighted_table["MG_final"] - mg_mean) ** 2
me_sq_diff = (final_weighted_table["ME_final"] - me_mean) ** 2
mw_sq_diff = (final_weighted_table["MW_final"] - mw_mean) ** 2

mg_sd = np.sqrt(mg_sq_diff.mean())
me_sd = np.sqrt(me_sq_diff.mean())
mw_sd = np.sqrt(mw_sq_diff.mean())

# --- Step 2: Ideal Best (A+) and Ideal Worst (A-) ---
A_plus = final_weighted_table[["MG_final", "ME_final", "MW_final"]].max()
A_minus = final_weighted_table[["MG_final", "ME_final", "MW_final"]].min()

# --- Step 3: Distances from A+ using root sum (D_plus_root_sum) ---
diff_plus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_plus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_plus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_plus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_plus_root_sum = np.sqrt(M) + np.sqrt(E) + np.sqrt(H)

    diff_plus.append({"Feature": row["Feature"], "D_plus_root_sum": D_plus_root_sum})

diff_df_plus = pd.DataFrame(diff_plus)

# --- Step 4: Distances from A- using root sum (D_minus_root_sum) ---
diff_minus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_minus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_minus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_minus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_minus_root_sum = np.sqrt(M) + np.sqrt(E) + np.sqrt(H)

    diff_minus.append({"Feature": row["Feature"], "D_minus_root_sum": D_minus_root_sum})

diff_df_minus = pd.DataFrame(diff_minus)

# --- Step 5: Merge and compute PC + OC + Final Score ---
pc_df = diff_df_plus.merge(diff_df_minus, on="Feature", how="inner")

pc_df["PC"] = pc_df["D_minus_root_sum"] / (pc_df["D_plus_root_sum"] + pc_df["D_minus_root_sum"])
pc_df["OC"] = 1 / (1 + pc_df["D_plus_root_sum"])
pc_df["Score"] = 0.5 * pc_df["PC"] + 0.5 * pc_df["OC"]
pc_df["Rank"] = pc_df["Score"].rank(ascending=False, method="dense").astype(int)

print("\nPC, OC, and Combined Score per feature:")
print(pc_df[["Feature", "D_plus_root_sum", "D_minus_root_sum", "PC", "OC", "Score", "Rank"]].to_string(index=False))

## SPOTIS

In [ ]:
# Step 3: Cap values at 1
merged["MG_phi_capped"] = merged["MG_phi"].apply(lambda x: min(x, 1))
merged["ME_phi_capped"] = merged["ME_phi"].apply(lambda x: min(x, 1))
merged["MW_phi_capped"] = merged["MW_phi"].apply(lambda x: min(x, 1))

# Step 4: Final table with original, multiplied and capped values
phi_table_final = merged[[
    "Feature", "MG", "ME", "MW", "phi",
    "MG_phi", "ME_phi", "MW_phi",
    "MG_phi_capped", "ME_phi_capped", "MW_phi_capped"
]]

print("\nFinal Table with feature-wise multiplier applied and capped at 1:\n")
print(phi_table_final.to_string(index=False))

In [ ]:
# Step 3: Cap values at 1
merged["MG_phi_capped"] = merged["MG_phi"].apply(lambda x: min(x, 1))
merged["ME_phi_capped"] = merged["ME_phi"].apply(lambda x: min(x, 1))
merged["MW_phi_capped"] = merged["MW_phi"].apply(lambda x: min(x, 1))

# Step 3.1: Compute (1 - capped values)
merged["1_minus_MG_phi_capped"] = 1 - merged["MG_phi_capped"]
merged["1_minus_ME_phi_capped"] = 1 - merged["ME_phi_capped"]
merged["1_minus_MW_phi_capped"] = 1 - merged["MW_phi_capped"]

# Step 4: Final table with all values
phi_table_final = merged[[
    "Feature", "MG", "ME", "MW", "phi",
    "MG_phi", "ME_phi", "MW_phi",
    "MG_phi_capped", "ME_phi_capped", "MW_phi_capped",
    "1_minus_MG_phi_capped", "1_minus_ME_phi_capped", "1_minus_MW_phi_capped"
]]

print("\nFinal Table with feature-wise multiplier applied, capped at 1, and (1 - capped):\n")
print(phi_table_final.to_string(index=False))

In [ ]:
# Step 5: Calculate feature-wise average after (1 - capped value)
phi_table_final["SPOTIS"] = (
    (1 - phi_table_final["MG_phi_capped"]) +
    (1 - phi_table_final["ME_phi_capped"]) +
    (1 - phi_table_final["MW_phi_capped"])
) / 3

print("\nFinal Table with feature-wise final score:\n")
print(phi_table_final.to_string(index=False))

In [ ]:
# Step 6: Sort by SPOTIS and assign ranking
phi_table_final = phi_table_final.sort_values(by="SPOTIS", ascending=True).reset_index(drop=True)
phi_table_final["Rank"] = phi_table_final.index + 1

print("\nFinal SPOTIS ranking table:\n")
print(phi_table_final.to_string(index=False))

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean & SD ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

mg_sq_diff = (final_weighted_table["MG_final"] - mg_mean)**2
me_sq_diff = (final_weighted_table["ME_final"] - me_mean)**2
mw_sq_diff = (final_weighted_table["MW_final"] - mw_mean)**2

mg_sd = np.sqrt(mg_sq_diff.mean())
me_sd = np.sqrt(me_sq_diff.mean())
mw_sd = np.sqrt(mw_sq_diff.mean())

# --- Step 2: Ideal Best (A+) and Ideal Worst (A-) ---
A_plus = final_weighted_table[["MG_final","ME_final","MW_final"]].max()
A_minus = final_weighted_table[["MG_final","ME_final","MW_final"]].min()

# --- Step 3: Distances from A+ (D_plus) ---
diff_plus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_plus["MG_final"]) / (mg_sd if mg_sd!=0 else 1)
    ME_abs = abs(row["ME_final"] - A_plus["ME_final"]) / (me_sd if me_sd!=0 else 1)
    MW_abs = abs(row["MW_final"] - A_plus["MW_final"]) / (mw_sd if mw_sd!=0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_plus = (np.log10(1+M))**2 + (np.log10(1+E))**2 + (np.log10(1+H))**2
    diff_plus.append({"Feature": row["Feature"], "D_plus": D_plus})

diff_df_plus = pd.DataFrame(diff_plus)

# --- Step 4: Distances from A- (D_minus) ---
diff_minus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_minus["MG_final"]) / (mg_sd if mg_sd!=0 else 1)
    ME_abs = abs(row["ME_final"] - A_minus["ME_final"]) / (me_sd if me_sd!=0 else 1)
    MW_abs = abs(row["MW_final"] - A_minus["MW_final"]) / (mw_sd if mw_sd!=0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_minus = (np.log10(1+M))**2 + (np.log10(1+E))**2 + (np.log10(1+H))**2
    diff_minus.append({"Feature": row["Feature"], "D_minus": D_minus})

diff_df_minus = pd.DataFrame(diff_minus)

# --- Step 5: Merge D+ and D- ---
pc_df = diff_df_plus.merge(diff_df_minus, on="Feature")

# --- Step 6: Assume phi_table_final already has capped phi values ---
phi_table_final["SPOTIS"] = (
    (1 - phi_table_final["MG_phi_capped"]) +
    (1 - phi_table_final["ME_phi_capped"]) +
    (1 - phi_table_final["MW_phi_capped"])
) / 3

# --- Step 7: Column-wise min and max ---
summary_stats = pd.DataFrame({
    "Metric": ["D_plus", "D_minus", "SPOTIS"],
    "Min": [
        pc_df["D_plus"].min(),
        pc_df["D_minus"].min(),
        phi_table_final["SPOTIS"].min()
    ],
    "Max": [
        pc_df["D_plus"].max(),
        pc_df["D_minus"].max(),
        phi_table_final["SPOTIS"].max()
    ]
})

# --- Step 8: Merge everything to display feature-wise values with min/max ---
feature_summary = pc_df.merge(
    phi_table_final[["Feature", "SPOTIS"]],
    on="Feature"
)

print("\nFeature-wise D_plus, D_minus, SPOTIS and Column-wise Min/Max:\n")
print(feature_summary.to_string(index=False))
print("\nColumn-wise Min and Max:\n")
print(summary_stats.to_string(index=False))

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean & SD ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

mg_sd = np.sqrt(((final_weighted_table["MG_final"] - mg_mean)**2).mean())
me_sd = np.sqrt(((final_weighted_table["ME_final"] - me_mean)**2).mean())
mw_sd = np.sqrt(((final_weighted_table["MW_final"] - mw_mean)**2).mean())

# --- Step 2: Ideal Best (A+) and Ideal Worst (A-) ---
A_plus = final_weighted_table[["MG_final","ME_final","MW_final"]].max()
A_minus = final_weighted_table[["MG_final","ME_final","MW_final"]].min()

# --- Step 3: Distances from A+ (D_plus) ---
diff_plus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_plus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_plus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_plus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_plus = (np.log10(1 + M))**2 + (np.log10(1 + E))**2 + (np.log10(1 + H))**2
    diff_plus.append({"Feature": row["Feature"], "D_plus": D_plus})

diff_df_plus = pd.DataFrame(diff_plus)

# --- Step 4: Distances from A- (D_minus) ---
diff_minus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_minus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_minus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_minus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_minus = (np.log10(1 + M))**2 + (np.log10(1 + E))**2 + (np.log10(1 + H))**2
    diff_minus.append({"Feature": row["Feature"], "D_minus": D_minus})

diff_df_minus = pd.DataFrame(diff_minus)

# --- Step 5: Merge D+ and D- ---
feature_df = diff_df_plus.merge(diff_df_minus, on="Feature")

# --- Step 6: Compute SPOTIS from capped phi values ---
phi_table_final["SPOTIS"] = (
    (1 - phi_table_final["MG_phi_capped"]) +
    (1 - phi_table_final["ME_phi_capped"]) +
    (1 - phi_table_final["MW_phi_capped"])
) / 3

feature_df = feature_df.merge(phi_table_final[["Feature", "SPOTIS"]], on="Feature")

# --- Step 7: Column-wise min and max ---
D_plus_min = feature_df["D_plus"].min()
D_plus_max = feature_df["D_plus"].max()
D_minus_min = feature_df["D_minus"].min()
D_minus_max = feature_df["D_minus"].max()
SPOTIS_min = feature_df["SPOTIS"].min()
SPOTIS_max = feature_df["SPOTIS"].max()

# --- Step 8: Feature-wise Normalization ---
feature_df["D_plus_NORM"] = (D_plus_max - feature_df["D_plus"]) / (D_plus_max - D_plus_min if D_plus_max != D_plus_min else 1)
feature_df["SPOTIS_NORM"] = (SPOTIS_max - feature_df["SPOTIS"]) / (SPOTIS_max - SPOTIS_min if SPOTIS_max != SPOTIS_min else 1)
feature_df["D_minus_NORM"] = (feature_df["D_minus"] - D_minus_min) / (D_minus_max - D_minus_min if D_minus_max != D_minus_min else 1)

# --- Step 9: Display ---
summary_stats = pd.DataFrame({
    "Metric": ["D_plus", "D_minus", "SPOTIS"],
    "Min": [D_plus_min, D_minus_min, SPOTIS_min],
    "Max": [D_plus_max, D_minus_max, SPOTIS_max]
})

print("\nFeature-wise Values with Normalization:\n")
print(feature_df.to_string(index=False))

print("\nColumn-wise Min and Max:\n")
print(summary_stats.to_string(index=False))

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean & SD ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

mg_sd = np.sqrt(((final_weighted_table["MG_final"] - mg_mean)**2).mean())
me_sd = np.sqrt(((final_weighted_table["ME_final"] - me_mean)**2).mean())
mw_sd = np.sqrt(((final_weighted_table["MW_final"] - mw_mean)**2).mean())

# --- Step 2: Ideal Best (A+) and Ideal Worst (A-) ---
A_plus = final_weighted_table[["MG_final","ME_final","MW_final"]].max()
A_minus = final_weighted_table[["MG_final","ME_final","MW_final"]].min()

# --- Step 3: Distances from A+ (D_plus) ---
diff_plus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_plus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_plus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_plus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_plus = (np.log10(1+M))**2 + (np.log10(1+E))**2 + (np.log10(1+H))**2
    diff_plus.append({"Feature": row["Feature"], "D_plus": D_plus})

diff_df_plus = pd.DataFrame(diff_plus)

# --- Step 4: Distances from A- (D_minus) ---
diff_minus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_minus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_minus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_minus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_minus = (np.log10(1+M))**2 + (np.log10(1+E))**2 + (np.log10(1+H))**2
    diff_minus.append({"Feature": row["Feature"], "D_minus": D_minus})

diff_df_minus = pd.DataFrame(diff_minus)

# --- Step 5: Merge D+ and D- ---
feature_df = diff_df_plus.merge(diff_df_minus, on="Feature")

# --- Step 6: Compute SPOTIS from capped phi values ---
phi_table_final["SPOTIS"] = (
    (1 - phi_table_final["MG_phi_capped"]) +
    (1 - phi_table_final["ME_phi_capped"]) +
    (1 - phi_table_final["MW_phi_capped"])
) / 3

feature_df = feature_df.merge(phi_table_final[["Feature", "SPOTIS"]], on="Feature")

# --- Step 7: Column-wise min and max ---
D_plus_min, D_plus_max = feature_df["D_plus"].min(), feature_df["D_plus"].max()
D_minus_min, D_minus_max = feature_df["D_minus"].min(), feature_df["D_minus"].max()
SPOTIS_min, SPOTIS_max = feature_df["SPOTIS"].min(), feature_df["SPOTIS"].max()

# --- Step 8: Feature-wise Normalization ---
feature_df["D_plus_NORM"] = (D_plus_max - feature_df["D_plus"]) / (D_plus_max - D_plus_min if D_plus_max != D_plus_min else 1)
feature_df["SPOTIS_NORM"] = (SPOTIS_max - feature_df["SPOTIS"]) / (SPOTIS_max - SPOTIS_min if SPOTIS_max != SPOTIS_min else 1)
feature_df["D_minus_NORM"] = (feature_df["D_minus"] - D_minus_min) / (D_minus_max - D_minus_min if D_minus_max != D_minus_min else 1)

# --- Step 9: Feature-wise Average of Normalized Values ---
feature_df["Average_NORM"] = feature_df[["D_plus_NORM", "SPOTIS_NORM", "D_minus_NORM"]].mean(axis=1)

# --- Step 10: Ranking based on Average_NORM ---
feature_df["Rank"] = feature_df["Average_NORM"].rank(ascending=False, method="dense").astype(int)

# --- Step 11: Display ---
summary_stats = pd.DataFrame({
    "Metric": ["D_plus", "D_minus", "SPOTIS"],
    "Min": [D_plus_min, D_minus_min, SPOTIS_min],
    "Max": [D_plus_max, D_minus_max, SPOTIS_max]
})

print("\nFeature-wise Normalized Values, Average, and Ranking:\n")
print(feature_df.to_string(index=False))

print("\nColumn-wise Min and Max:\n")
print(summary_stats.to_string(index=False))

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean & SD ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

mg_sd = np.sqrt(((final_weighted_table["MG_final"] - mg_mean)**2).mean())
me_sd = np.sqrt(((final_weighted_table["ME_final"] - me_mean)**2).mean())
mw_sd = np.sqrt(((final_weighted_table["MW_final"] - mw_mean)**2).mean())

# --- Step 2: Ideal Best (A+) and Ideal Worst (A-) ---
A_plus = final_weighted_table[["MG_final","ME_final","MW_final"]].max()
A_minus = final_weighted_table[["MG_final","ME_final","MW_final"]].min()

# --- Step 3: Distances from A+ (D_plus_sqrt) ---
diff_plus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_plus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_plus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_plus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_plus_sqrt = np.sqrt((np.log10(1 + M))**2 + (np.log10(1 + E))**2 + (np.log10(1 + H))**2)
    diff_plus.append({"Feature": row["Feature"], "D_plus_sqrt": D_plus_sqrt})

diff_df_plus = pd.DataFrame(diff_plus)

# --- Step 4: Distances from A- (D_minus_sqrt) ---
diff_minus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_minus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_minus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_minus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_minus_sqrt = np.sqrt((np.log10(1 + M))**2 + (np.log10(1 + E))**2 + (np.log10(1 + H))**2)
    diff_minus.append({"Feature": row["Feature"], "D_minus_sqrt": D_minus_sqrt})

diff_df_minus = pd.DataFrame(diff_minus)

# --- Step 5: Merge D+ and D- ---
feature_df = diff_df_plus.merge(diff_df_minus, on="Feature")

# --- Step 6: Compute SPOTIS from capped phi values ---
phi_table_final["SPOTIS"] = (
    (1 - phi_table_final["MG_phi_capped"]) +
    (1 - phi_table_final["ME_phi_capped"]) +
    (1 - phi_table_final["MW_phi_capped"])
) / 3

feature_df = feature_df.merge(phi_table_final[["Feature", "SPOTIS"]], on="Feature")

# --- Step 7: Column-wise min and max ---
summary_stats = pd.DataFrame({
    "Metric": ["D_plus_sqrt", "D_minus_sqrt", "SPOTIS"],
    "Min": [
        feature_df["D_plus_sqrt"].min(),
        feature_df["D_minus_sqrt"].min(),
        feature_df["SPOTIS"].min()
    ],
    "Max": [
        feature_df["D_plus_sqrt"].max(),
        feature_df["D_minus_sqrt"].max(),
        feature_df["SPOTIS"].max()
    ]
})

print("\nFeature-wise D_plus_sqrt, D_minus_sqrt, SPOTIS:\n")
print(feature_df.to_string(index=False))

print("\nColumn-wise Min and Max:\n")
print(summary_stats.to_string(index=False))

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean & SD ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

mg_sd = np.sqrt(((final_weighted_table["MG_final"] - mg_mean)**2).mean())
me_sd = np.sqrt(((final_weighted_table["ME_final"] - me_mean)**2).mean())
mw_sd = np.sqrt(((final_weighted_table["MW_final"] - mw_mean)**2).mean())

# --- Step 2: Ideal Best (A+) and Ideal Worst (A-) ---
A_plus = final_weighted_table[["MG_final","ME_final","MW_final"]].max()
A_minus = final_weighted_table[["MG_final","ME_final","MW_final"]].min()

# --- Step 3: Distances from A+ (D_plus_sqrt) ---
diff_plus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_plus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_plus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_plus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_plus_sqrt = np.sqrt((np.log10(1 + M))**2 + (np.log10(1 + E))**2 + (np.log10(1 + H))**2)
    diff_plus.append({"Feature": row["Feature"], "D_plus_sqrt": D_plus_sqrt})

diff_df_plus = pd.DataFrame(diff_plus)

# --- Step 4: Distances from A- (D_minus_sqrt) ---
diff_minus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_minus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_minus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_minus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_minus_sqrt = np.sqrt((np.log10(1 + M))**2 + (np.log10(1 + E))**2 + (np.log10(1 + H))**2)
    diff_minus.append({"Feature": row["Feature"], "D_minus_sqrt": D_minus_sqrt})

diff_df_minus = pd.DataFrame(diff_minus)

# --- Step 5: Merge D+ and D- ---
feature_df = diff_df_plus.merge(diff_df_minus, on="Feature")

# --- Step 6: Compute SPOTIS from capped phi values ---
phi_table_final["SPOTIS"] = (
    (1 - phi_table_final["MG_phi_capped"]) +
    (1 - phi_table_final["ME_phi_capped"]) +
    (1 - phi_table_final["MW_phi_capped"])
) / 3

feature_df = feature_df.merge(phi_table_final[["Feature", "SPOTIS"]], on="Feature")

# --- Step 7: Column-wise min and max ---
D_plus_min, D_plus_max = feature_df["D_plus_sqrt"].min(), feature_df["D_plus_sqrt"].max()
D_minus_min, D_minus_max = feature_df["D_minus_sqrt"].min(), feature_df["D_minus_sqrt"].max()
SPOTIS_min, SPOTIS_max = feature_df["SPOTIS"].min(), feature_df["SPOTIS"].max()

# --- Step 8: Feature-wise Normalization ---
feature_df["D_plus_NORM"] = (D_plus_max - feature_df["D_plus_sqrt"]) / (D_plus_max - D_plus_min if D_plus_max != D_plus_min else 1)
feature_df["SPOTIS_NORM"] = (SPOTIS_max - feature_df["SPOTIS"]) / (SPOTIS_max - SPOTIS_min if SPOTIS_max != SPOTIS_min else 1)
feature_df["D_minus_NORM"] = (feature_df["D_minus_sqrt"] - D_minus_min) / (D_minus_max - D_minus_min if D_minus_max != D_minus_min else 1)

# --- Step 9: Feature-wise Average of Normalized Values ---
feature_df["Average_NORM"] = feature_df[["D_plus_NORM", "SPOTIS_NORM", "D_minus_NORM"]].mean(axis=1)

# --- Step 10: Ranking based on Average_NORM ---
feature_df["Rank"] = feature_df["Average_NORM"].rank(ascending=False, method="dense").astype(int)

# --- Step 11: Display ---
summary_stats = pd.DataFrame({
    "Metric": ["D_plus_sqrt", "D_minus_sqrt", "SPOTIS"],
    "Min": [D_plus_min, D_minus_min, SPOTIS_min],
    "Max": [D_plus_max, D_minus_max, SPOTIS_max]
})

print("\nFeature-wise Normalized Values, Average, and Ranking:\n")
print(feature_df.to_string(index=False))

print("\nColumn-wise Min and Max:\n")
print(summary_stats.to_string(index=False))

## ROOT SUM WISE NORMALIZATION RANK

In [ ]:
import numpy as np
import pandas as pd

# --- Step 1: Column-wise mean & SD ---
mg_mean = final_weighted_table["MG_final"].mean()
me_mean = final_weighted_table["ME_final"].mean()
mw_mean = final_weighted_table["MW_final"].mean()

mg_sd = np.sqrt(((final_weighted_table["MG_final"] - mg_mean)**2).mean())
me_sd = np.sqrt(((final_weighted_table["ME_final"] - me_mean)**2).mean())
mw_sd = np.sqrt(((final_weighted_table["MW_final"] - mw_mean)**2).mean())

# --- Step 2: Ideal Best (A+) and Ideal Worst (A-) ---
A_plus = final_weighted_table[["MG_final","ME_final","MW_final"]].max()
A_minus = final_weighted_table[["MG_final","ME_final","MW_final"]].min()

# --- Step 3: Distances from A+ using root sum (D_plus_root_sum) ---
diff_plus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_plus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_plus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_plus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_plus_root_sum = np.sqrt(M) + np.sqrt(E) + np.sqrt(H)
    diff_plus.append({"Feature": row["Feature"], "D_plus_root_sum": D_plus_root_sum})

diff_df_plus = pd.DataFrame(diff_plus)

# --- Step 4: Distances from A- using root sum (D_minus_root_sum) ---
diff_minus = []
for _, row in final_weighted_table.iterrows():
    MG_abs = abs(row["MG_final"] - A_minus["MG_final"]) / (mg_sd if mg_sd != 0 else 1)
    ME_abs = abs(row["ME_final"] - A_minus["ME_final"]) / (me_sd if me_sd != 0 else 1)
    MW_abs = abs(row["MW_final"] - A_minus["MW_final"]) / (mw_sd if mw_sd != 0 else 1)

    M = MG_abs + ME_abs + MW_abs
    E = np.sqrt(MG_abs**2 + ME_abs**2 + MW_abs**2)
    H = max(MG_abs, ME_abs, MW_abs)

    D_minus_root_sum = np.sqrt(M) + np.sqrt(E) + np.sqrt(H)
    diff_minus.append({"Feature": row["Feature"], "D_minus_root_sum": D_minus_root_sum})

diff_df_minus = pd.DataFrame(diff_minus)

# --- Step 5: Merge D+ and D- ---
feature_df = diff_df_plus.merge(diff_df_minus, on="Feature")

# --- Step 6: Compute SPOTIS from capped phi values ---
phi_table_final["SPOTIS"] = (
    (1 - phi_table_final["MG_phi_capped"]) +
    (1 - phi_table_final["ME_phi_capped"]) +
    (1 - phi_table_final["MW_phi_capped"])
) / 3

feature_df = feature_df.merge(phi_table_final[["Feature", "SPOTIS"]], on="Feature")

# --- Step 7: Column-wise min and max ---
D_plus_min, D_plus_max = feature_df["D_plus_root_sum"].min(), feature_df["D_plus_root_sum"].max()
D_minus_min, D_minus_max = feature_df["D_minus_root_sum"].min(), feature_df["D_minus_root_sum"].max()
SPOTIS_min, SPOTIS_max = feature_df["SPOTIS"].min(), feature_df["SPOTIS"].max()

# --- Step 8: Feature-wise Normalization ---
feature_df["D_plus_NORM"] = (D_plus_max - feature_df["D_plus_root_sum"]) / (D_plus_max - D_plus_min if D_plus_max != D_plus_min else 1)
feature_df["SPOTIS_NORM"] = (SPOTIS_max - feature_df["SPOTIS"]) / (SPOTIS_max - SPOTIS_min if SPOTIS_max != SPOTIS_min else 1)
feature_df["D_minus_NORM"] = (feature_df["D_minus_root_sum"] - D_minus_min) / (D_minus_max - D_minus_min if D_minus_max != D_minus_min else 1)

# --- Step 9: Feature-wise Average of Normalized Values ---
feature_df["Average_NORM"] = feature_df[["D_plus_NORM", "SPOTIS_NORM", "D_minus_NORM"]].mean(axis=1)

# --- Step 10: Ranking based on Average_NORM ---
feature_df["Rank"] = feature_df["Average_NORM"].rank(ascending=False, method="dense").astype(int)

# --- Step 11: Display ---
summary_stats = pd.DataFrame({
    "Metric": ["D_plus_root_sum", "D_minus_root_sum", "SPOTIS"],
    "Min": [D_plus_min, D_minus_min, SPOTIS_min],
    "Max": [D_plus_max, D_minus_max, SPOTIS_max]
})

print("\nFeature-wise Normalized Values, Average, and Ranking:\n")
print(feature_df.to_string(index=False))

print("\nColumn-wise Min and Max:\n")
print(summary_stats.to_string(index=False))

## REVERSAL