In [1]:
import pandas as pd

df = pd.read_csv("/content/Final Primary_dataset_from_Indonesian_Private_University.csv")

In [2]:
display(df)

,age,Gender,Work tenure,Education,Job position,Unnamed: 5,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,...,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,"1. In last 3 months, I am thinking of quitting from this office/organization (Dalam 3 bulan terakhir, saya berpikir untuk berhenti dari kantor/organisasi ini)","2. In last 3 months, I am searching for an alternative job (Dalam 3 bulan terakhir, saya mencari alternatif pekerjaan lain)","3. In last 3 months, I have low work motivation (Dalam 3 bulan terakhir, motivasi kerja saya rendah)",TOI (turnover intention)
0,26-35 year,Male,3 - 5 years,Master's degree,Senior lecturer,NaN,less than 40,4,3,3,...,3,5.001.000IDR-10.000.000 IDR,3,3,3,3,3,3,3,1
1,26-35 year,Female,Less than 2 years,Bachelor's degree,Lecturer,NaN,less than 40,3,4,4,...,4,3.000.000 IDR -5.000.000 IDR,4,4,4,3,2,2,2,0
2,46-55 year,Female,more than 5 years,Doctorate or other advanced degree,Professor,NaN,40-45,3,4,4,...,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,4,4,4,4,4,4,1
3,more than 56 year,Female,more than 5 years,Doctorate or other advanced degree,Professor,NaN,51-55,3,4,4,...,4,Greater than 20.000.000 IDR (Lebih besar dari ...,4,5,5,4,1,1,2,0
4,26-35 year,Female,3 - 5 years,Bachelor's degree,Lecturer,NaN,40-45,3,2,5,...,4,3.000.000 IDR -5.000.000 IDR,3,5,5,4,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,18-25 year,Male,Less than 2 years,Masters,Lecturer,NaN,less than 40,5,5,5,...,5,3.000.000 IDR -5.000.000 IDR,5,5,4,5,2,2,2,0
522,36-45 year,Male,3 - 5 years,Bachelor's degree,Lecturer,NaN,51-55,2,2,3,...,2,3.000.000 IDR -5.000.000 IDR,2,3,2,1,5,5,5,1
523,36-45 year,Female,more than 5 years,Master's degree,Lecturer,NaN,51-55,4,2,5,...,4,5.001.000IDR-10.000.000 IDR,3,4,5,5,2,2,4,0
524,more than 56 year,Female,more than 5 years,Master's degree,Senior lecturer,NaN,40-45,4,4,4,...,4,3.000.000 IDR -5.000.000 IDR,4,5,5,4,1,1,2,0
525,more than 56 year,Male,more than 5 years,Master's degree,Lecturer,NaN,less than 40,4,4,4,...,4,10.000.000 IDR-20.000.000 IDR,4,4,4,4,1,2,2,0

In [3]:
del df["Unnamed: 5"]

In [18]:
display(df)

,age,Gender,Work tenure,Education,Job position,working hour,satisfaction with workload,satisfied compensation,good relationship with peers,satisfied with career and opportunity,satisfied with job profession,monthly salary,satisfied with work-life balance,work is meaningful,family support,mentally well and do not have anxiety,TOI (turnover intention)
0,26.0,Male,3.0,Master's degree,Senior lecturer,40.0,4,3,3,3,3,5.001,3,3,3,3,1
1,26.0,Female,2.0,Bachelor's degree,Lecturer,40.0,3,4,4,4,4,3.000,4,4,4,3,0
2,46.0,Female,5.0,Doctorate or other advanced degree,Professor,40.0,3,4,4,4,4,20.000,4,4,4,4,1
3,56.0,Female,5.0,Doctorate or other advanced degree,Professor,51.0,3,4,4,4,4,20.000,4,5,5,4,0
4,26.0,Female,3.0,Bachelor's degree,Lecturer,40.0,3,2,5,3,4,3.000,3,5,5,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,18.0,Male,2.0,Masters,Lecturer,40.0,5,5,5,5,5,3.000,5,5,4,5,0
522,36.0,Male,3.0,Bachelor's degree,Lecturer,51.0,2,2,3,2,2,3.000,2,3,2,1,1
523,36.0,Female,5.0,Master's degree,Lecturer,51.0,4,2,5,4,4,5.001,3,4,5,5,0
524,56.0,Female,5.0,Master's degree,Senior lecturer,40.0,4,4,4,4,4,3.000,4,5,5,4,0
525,56.0,Male,5.0,Master's degree,Lecturer,40.0,4,4,4,4,4,10.000,4,4,4,4,0

In [20]:
# Print all column names
print(df.columns.tolist())

['age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour', 'satisfaction with workload', 'satisfied compensation', 'good relationship with peers', 'satisfied with career and opportunity', 'satisfied with job profession', 'monthly salary', 'satisfied with work-life balance', 'work is meaningful', 'family support', 'mentally well and do not have anxiety', 'TOI (turnover intention)']

In [22]:
# See all unique values
print(df["good relationship with peers"].unique())

# Count frequency of each value
print(df["good relationship with peers"].value_counts())

[3 4 5 2]
good relationship with peers
4    242
3    134
5     78
2     72
Name: count, dtype: int64

In [23]:
# See all unique values
print(df["family support"].unique())

# Count frequency of each value
print(df["family support"].value_counts())

[3 4 5 2 1]
family support
4    237
3    112
2     98
5     77
1      2
Name: count, dtype: int64

In [24]:
# See all unique values
print(df["satisfaction with workload"].unique())

# Count frequency of each value
print(df["satisfaction with workload"].value_counts())

[4 3 2 5 1]
satisfaction with workload
4    287
2    132
3     64
5     33
1     10
Name: count, dtype: int64

In [26]:
import pandas as pd
import numpy as np

# --- Load & normalize column names ---
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'  # adjust if needed
df = pd.read_csv(file_path)
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

# --- Columns of interest ---
target = 'TOI (turnover intention)'
cols = [
    'satisfaction with workload',
    'good relationship with peers',
    'family support'
]

# --- Keep needed columns, coerce to numeric, drop missing ---
df_small = df[cols + [target]].copy()
for c in cols:
    df_small[c] = pd.to_numeric(df_small[c], errors='coerce')
df_small[target] = pd.to_numeric(df_small[target], errors='coerce').astype('Int64')
df_small = df_small.dropna(subset=cols + [target])
df_small[target] = df_small[target].astype(int)

def toi_freq_table(col_name: str) -> pd.DataFrame:
    # counts of TOI=0/1 by each Likert value
    ct = pd.crosstab(df_small[col_name], df_small[target]).rename(columns={0: 'TOI=0', 1: 'TOI=1'})
    if 'TOI=0' not in ct.columns: ct['TOI=0'] = 0
    if 'TOI=1' not in ct.columns: ct['TOI=1'] = 0
    ct = ct[['TOI=0', 'TOI=1']].sort_index()
    ct['Total'] = ct['TOI=0'] + ct['TOI=1']
    ct['TOI=1 rate (%)'] = (ct['TOI=1'] / ct['Total'] * 100).round(2)
    ct.index.name = f'{col_name} (value)'
    return ct.reset_index()

# --- Compute & print tables ---
tables = {c: toi_freq_table(c) for c in cols}
for name, table in tables.items():
    print(f'\n=== TOI frequency by value — {name} ===')
    print(table.to_string(index=False))

# --- (Optional) Save to CSVs ---
# for name, table in tables.items():
#     safe = name.replace(' ', '_')
#     table.to_csv(f'{safe}_TOI_frequency.csv', index=False)

=== TOI frequency by value — satisfaction with workload ===
 satisfaction with workload (value)  TOI=0  TOI=1  Total  TOI=1 rate (%)
                                  1      1      9     10           90.00
                                  2     10    122    132           92.42
                                  3     37     27     64           42.19
                                  4    246     41    287           14.29
                                  5     31      2     33            6.06

=== TOI frequency by value — good relationship with peers ===
 good relationship with peers (value)  TOI=0  TOI=1  Total  TOI=1 rate (%)
                                    2      5     67     72           93.06
                                    3     60     74    134           55.22
                                    4    191     51    242           21.07
                                    5     69      9     78           11.54

=== TOI frequency by value — family support ===
 family support (value)  TOI=0  TOI=1  Total  TOI=1 rate (%)
                      1      1      1      2           50.00
                      2      7     91     98           92.86
                      3     55     57    112           50.89
                      4    197     40    237           16.88
                      5     65     12     77           15.58

In [5]:
import pandas as pd
import numpy as np
import scipy.stats as stats

# --- Load dataset ---
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'
df = pd.read_csv(file_path)

# --- Clean column names (strip + collapse spaces) ---
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

# --- Features & target ---
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

# --- Simple binning for continuous variables ---
continuous = ['age', 'Work tenure', 'working hour', 'monthly salary']
for col in continuous:
    if col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
        # 4 bins (quartiles); adjust if you want specific ranges
        df[col+'_bin'] = pd.qcut(df[col], q=4, duplicates='drop')
        features[features.index(col)] = col+'_bin'   # replace with binned version

# --- Chi-Square calculation ---
results = []
for col in features:
    if col not in df.columns:
        continue
    contingency = pd.crosstab(df[col], df[target])
    chi2, p, _, _ = stats.chi2_contingency(contingency)
    results.append([col, chi2, p])

# --- Results table ---
chi_square_table = pd.DataFrame(results, columns=["Feature", "Chi2", "p-value"])\
                     .sort_values(by="Chi2", ascending=False)\
                     .reset_index(drop=True)

print(chi_square_table)

                                  Feature        Chi2       p-value
0              satisfaction with workload  260.130800  4.273685e-55
1   mentally well and do not have anxiety  221.432640  9.217851e-47
2        satisfied with work-life balance  221.034705  1.122706e-46
3           satisfied with job profession  218.207880  4.899062e-47
4                  satisfied compensation  215.451589  1.784903e-45
5   satisfied with career and opportunity  196.795940  1.835194e-41
6                          family support  194.073987  7.059258e-41
7                      work is meaningful  179.963720  8.980506e-39
8            good relationship with peers  161.754571  7.664255e-35
9                            working hour  155.764546  1.183418e-32
10                                    age   41.350494  2.274146e-08
11                            Work tenure   33.301139  2.782391e-07
12                           Job position   23.863259  7.971734e-03
13                              Education   20.135328  5.284676e-03
14                         monthly salary    9.329574  2.521526e-02
15                                 Gender    2.639665  1.042255e-01

In [6]:
# --- Setup ---
import pandas as pd
import numpy as np
from sklearn.feature_selection import f_classif

# 1) Load your CSV (adjust path if needed)
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'
df = pd.read_csv(file_path)

# 2) Clean column names: strip, collapse multiple spaces
df.columns = (
    df.columns
      .str.strip()
      .str.replace(r'\s+', ' ', regex=True)
)

# 3) Define features + target
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

# 4) Keep only your features + target
df = df[features + [target]].copy()

# 5) Drop rows with missing target & convert to numeric
df = df.dropna(subset=[target])
df[target] = pd.to_numeric(df[target], errors='coerce').astype(int)

# 6) Split X and y
X_raw = df[features].copy()
y = df[target]

# 7) Identify numeric vs categorical
numeric_cols = X_raw.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = [c for c in X_raw.columns if c not in numeric_cols]

# 8) One-hot encode categoricals (safe separator)
SAFE_SEP = '§'
X_cat = pd.get_dummies(
    X_raw[categorical_cols],
    prefix=categorical_cols,
    prefix_sep=SAFE_SEP,
    drop_first=True,   # drop baseline level
    dtype=np.uint8
) if categorical_cols else pd.DataFrame(index=X_raw.index)

# 9) Combine numeric + encoded categoricals
X_num = X_raw[numeric_cols].copy()
X = pd.concat([X_num, X_cat], axis=1)

# Drop any rows with NaNs in features
mask = X.notna().all(axis=1)
X = X.loc[mask]
y = y.loc[mask]

# 10) Run ANOVA F-test
f_values, p_values = f_classif(X.values, y.values)

per_column = pd.DataFrame({
    'Column': X.columns,
    'F_value': f_values,
    'p_value': p_values
}).sort_values('F_value', ascending=False).reset_index(drop=True)

# 11) Aggregate back to original features
def original_feature(col: str) -> str:
    return col.split(SAFE_SEP, 1)[0] if SAFE_SEP in col else col

per_column['Feature'] = per_column['Column'].map(original_feature)

agg = (per_column
       .groupby('Feature', as_index=False)
       .agg(F_value_max=('F_value', 'max'),
            p_value_min=('p_value', 'min'))
       .sort_values('F_value_max', ascending=False)
       .reset_index(drop=True))


print("\n ANOVA F ")
print(agg)

 ANOVA F
                                  Feature  F_value_max   p_value_min
0              satisfaction with workload   450.412687  1.326868e-72
1           satisfied with job profession   329.670618  1.637191e-57
2                  satisfied compensation   328.878742  2.089366e-57
3        satisfied with work-life balance   295.485226  7.570759e-53
4   mentally well and do not have anxiety   277.093544  2.956912e-50
5   satisfied with career and opportunity   265.188107  1.516218e-48
6                          family support   244.386499  1.705984e-45
7                      work is meaningful   229.705426  2.730146e-43
8            good relationship with peers   209.230822  3.837615e-40
9                            working hour   126.492767  1.947913e-26
10                            Work tenure    30.952897  4.222161e-08
11                                    age    10.030950  1.628997e-03
12                              Education     8.259292  4.218998e-03
13                           Job position     7.765880  5.517334e-03
14                         monthly salary     6.633074  1.028322e-02
15                                 Gender     2.985434  8.460595e-02

In [7]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import OrdinalEncoder

# 1) Load and normalize column names
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'
df = pd.read_csv(file_path)
df.columns = (
    df.columns
      .str.strip()
      .str.replace(r'\s+', ' ', regex=True)
)

# 2) Your features and target
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

# Keep only requested cols (drop rows missing target)
df = df[features + [target]].dropna(subset=[target])

# 3) Split categorical vs numeric from YOUR list
categorical_features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position',
    'working hour', 'monthly salary'
]
numeric_features = [c for c in features if c not in categorical_features]

# 4) Prepare X: encode categoricals, keep numeric as numeric
X_cat = df[categorical_features].astype('category')
X_num = df[numeric_features].apply(pd.to_numeric, errors='coerce')

# Drop rows with NaNs in numeric features to satisfy MI
row_mask = X_num.notna().all(axis=1)
X_cat = X_cat.loc[row_mask]
X_num = X_num.loc[row_mask]
y = df.loc[row_mask, target].astype(int)

# Ordinal-encode categoricals (just to convert strings→ints)
enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_cat_enc = pd.DataFrame(
    enc.fit_transform(X_cat),
    columns=categorical_features,
    index=X_cat.index
).astype(int)

# Combine back
X = pd.concat([X_cat_enc, X_num], axis=1)

# 5) Build the discrete_features mask (True for categoricals, False for numeric)
discrete_mask = [col in categorical_features for col in X.columns]

# 6) Run Mutual Information
mi_scores = mutual_info_classif(
    X.values, y.values,
    discrete_features=discrete_mask,
    random_state=42
)

mi_table = pd.DataFrame({
    "Feature": X.columns,
    "MI Score": mi_scores

}).sort_values("MI Score", ascending=False).reset_index(drop=True)

print(mi_table)

                                  Feature  MI Score
0              satisfaction with workload  0.260661
1        satisfied with work-life balance  0.256384
2           satisfied with job profession  0.232816
3                  satisfied compensation  0.229535
4   mentally well and do not have anxiety  0.218119
5   satisfied with career and opportunity  0.197362
6                          family support  0.180731
7                      work is meaningful  0.171876
8                            working hour  0.152510
9            good relationship with peers  0.139234
10                                    age  0.039701
11                            Work tenure  0.031212
12                           Job position  0.024117
13                              Education  0.020771
14                         monthly salary  0.009054
15                                 Gender  0.002803

In [8]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import OrdinalEncoder

# === 1) Load & normalize column names ===
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'  # <- adjust if needed
df = pd.read_csv(file_path)
df.columns = (
    df.columns
      .str.strip()
      .str.replace(r'\s+', ' ', regex=True)
)

# === 2) Your features & target (normalized names) ===
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

# Keep only requested columns and drop rows missing target
df = df[features + [target]].dropna(subset=[target])

# === 3) Split categorical vs numeric from YOUR list ===
categorical_features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position',
    'working hour', 'monthly salary'
]
numeric_features = [c for c in features if c not in categorical_features]

# Prepare X: encode categoricals, keep numeric as numeric
X_cat = df[categorical_features].astype('category')
X_num = df[numeric_features].apply(pd.to_numeric, errors='coerce')

# Drop rows with NaNs in numeric features (keeps MI happy)
row_mask = X_num.notna().all(axis=1)
X_cat = X_cat.loc[row_mask]
X_num = X_num.loc[row_mask]
y = df.loc[row_mask, target].astype(int)

enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_cat_enc = pd.DataFrame(
    enc.fit_transform(X_cat),
    columns=categorical_features,
    index=X_cat.index
).astype(int)

# Combine back
X = pd.concat([X_cat_enc, X_num], axis=1)

# Build the discrete_features mask (True for categoricals, False for numeric)
discrete_mask = [col in categorical_features for col in X.columns]

# === 4) Information Gain (Mutual Information) ===
IG_scores = mutual_info_classif(
    X.values, y.values,
    discrete_features=discrete_mask,
    random_state=42
)

ig_table = pd.DataFrame({
    "Feature": X.columns,
    "Information_Gain": IG_scores,
    "Type": ["categorical" if d else "numeric" for d in discrete_mask]
}).sort_values("Information_Gain", ascending=False).reset_index(drop=True)

print(ig_table)

                                  Feature  Information_Gain         Type
0              satisfaction with workload          0.260661      numeric
1        satisfied with work-life balance          0.256384      numeric
2           satisfied with job profession          0.232816      numeric
3                  satisfied compensation          0.229535      numeric
4   mentally well and do not have anxiety          0.218119      numeric
5   satisfied with career and opportunity          0.197362      numeric
6                          family support          0.180731      numeric
7                      work is meaningful          0.171876      numeric
8                            working hour          0.152510  categorical
9            good relationship with peers          0.139234      numeric
10                                    age          0.039701  categorical
11                            Work tenure          0.031212  categorical
12                           Job position          0.024117  categorical
13                              Education          0.020771  categorical
14                         monthly salary          0.009054  categorical
15                                 Gender          0.002803  categorical

In [9]:
# ===== LASSO (L1 Logistic) feature selection for TOI =====
# - Uses ONLY your declared features + target
# - One-hot encodes categoricals, scales Likert numerics
# - Cross-validated strength of regularization (C)
# - Produces per-column and grouped-by-feature tables and saves as CSVs

import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegressionCV

print("scikit-learn version:", sklearn.__version__)

# ---------- 1) Load & normalize column names ----------
file_path = '/content/Final Primary_dataset_from_Indonesian_Private_University.csv'  # <-- adjust if needed
df = pd.read_csv(file_path)
# strip ends & collapse multiple spaces to a single space (your CSV has extra spaces)
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

# ---------- 2) Your features and target (normalized names) ----------
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

# keep only your columns; drop rows with missing target
missing = [c for c in features + [target] if c not in df.columns]
if missing:
    raise KeyError(f"Missing columns after normalization: {missing}")

df = df[features + [target]].dropna(subset=[target])
y = df[target].astype(int)

# ---------- 3) Split numeric (Likert) vs categorical ----------
categorical_features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position',
    'working hour', 'monthly salary'
]
numeric_features = [c for c in features if c not in categorical_features]

# ensure Likert numerics are numeric
for col in numeric_features:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# drop rows with any missing in selected features
df = df.dropna(subset=features)
X = df[features]
y = df[target].astype(int)

# ---------- 4) Preprocessing: OHE for categoricals + scaling for numerics ----------
SAFE_SEP = '§'  # used to rebuild original feature names from dummies later

# Handle OneHotEncoder API differences across sklearn versions
# - <1.2: OneHotEncoder(..., sparse=False)
# - >=1.2: OneHotEncoder(..., sparse_output=False)
ohe_kwargs = dict(drop='first', handle_unknown='ignore')
ver = tuple(int(v) for v in sklearn.__version__.split('.')[:2])
if ver >= (1, 2):
    ohe_kwargs['sparse_output'] = False
else:
    ohe_kwargs['sparse'] = False

ohe = OneHotEncoder(**ohe_kwargs)
scaler = StandardScaler()

preprocess = ColumnTransformer(
    transformers=[
        ('cat', ohe, categorical_features),
        ('num', scaler, numeric_features),
    ],
    remainder='drop'
)

# ---------- 5) L1-penalized Logistic Regression with CV ----------
# We optimize F1 and use class_weight='balanced' for any class imbalance.
logreg_cv = LogisticRegressionCV(
    Cs=np.logspace(-2, 1, 8),  # search range for C (inverse of regularization)
    cv=StratifiedKFold(n_splits=3, shuffle=True, random_state=42),
    penalty='l1',
    solver='saga',             # supports l1 with class_weight
    scoring='f1',
    class_weight='balanced',
    max_iter=4000,
    n_jobs=-1,
    refit=True
)

pipe = Pipeline(steps=[('prep', preprocess), ('clf', logreg_cv)])
pipe.fit(X, y)

# ---------- 6) Recover feature names after preprocessing ----------
# Build Feature§Category names for one-hot columns so we can group later.
cat_feature_names = []
ohe_fitted = pipe.named_steps['prep'].named_transformers_['cat']
for feat, cats in zip(categorical_features, ohe_fitted.categories_):
    # drop='first' => first category is the baseline and not present in output
    for cat in cats[1:]:
        cat_feature_names.append(f"{feat}{SAFE_SEP}{cat}")

num_feature_names = numeric_features[:]  # unchanged by StandardScaler
all_feature_names = cat_feature_names + num_feature_names

# ---------- 7) Coefficients (LASSO shrinkage; zeros mean dropped) ----------
coefs = pipe.named_steps['clf'].coef_.ravel()
per_column = pd.DataFrame({
    'Column': all_feature_names,
    'Coefficient': coefs
})
per_column['Abs_Coeff'] = per_column['Coefficient'].abs()
per_column = per_column.sort_values('Abs_Coeff', ascending=False).reset_index(drop=True)

def original_feature_name(col: str) -> str:
    return col.split(SAFE_SEP, 1)[0] if SAFE_SEP in col else col

per_column['Feature'] = per_column['Column'].map(original_feature_name)

# Aggregate back to original feature:
# - Importance = sum of |coefficients| over its columns
# - NonZero_Columns = count of nonzero coefficients (survived lasso)
# - Max_Abs = largest |coef| among its columns
# - Columns = total columns contributed (1 for numeric; >1 for categoricals)
grouped = (
    per_column
    .groupby('Feature', as_index=False)
    .agg(Importance=('Abs_Coeff', 'sum'),
         NonZero_Columns=('Coefficient', lambda x: int(np.sum(x != 0))),
         Max_Abs=('Abs_Coeff', 'max'),
         Columns=('Column', 'count'))
    .sort_values('Importance', ascending=False)
    .reset_index(drop=True)
)

# ---------- 8) Show & save ----------
print("\n=== L1-Logistic (LASSO) — Per Column Coefficients (top 25) ===")
print(per_column.head(25))
print("\n=== L1-Logistic (LASSO) — Grouped by Feature ===")
print(grouped)


# Optional: quick glance at class balance
print("\nClass counts (TOI):")
print(y.value_counts())

scikit-learn version: 1.6.1

=== L1-Logistic (LASSO) — Per Column Coefficients (top 25) ===
                                          Column  Coefficient  Abs_Coeff  \
0                 Work tenure§Less than 2 years      1.300798   1.300798
1                         satisfied compensation    -0.827426   0.827426
2                     satisfaction with workload    -0.713693   0.713693
3          mentally well and do not have anxiety    -0.398365   0.398365
4                  satisfied with job profession    -0.267116   0.267116
5                                 family support    -0.248524   0.248524
6                      Education§Master's degree    -0.136890   0.136890
7                                    Gender§Male    -0.116763   0.116763
8                   good relationship with peers    -0.069503   0.069503
9                             work is meaningful    -0.061416   0.061416
10                  Education§Bachelor's degree      0.000000   0.000000
11                 Work tenure§Less than 2 years     0.000000   0.000000
12                 Work tenure§more than 5 years     0.000000   0.000000
13                                age§36-45 year     0.000000   0.000000
14                                age§46-55 year     0.000000   0.000000
15                                age§26-35 year     0.000000   0.000000
16                         age§more than 56 year     0.000000   0.000000
17             Job position§Associate professor      0.000000   0.000000
18  Education§Doctorate or other advanced degree     0.000000   0.000000
19                        Education§High School      0.000000   0.000000
20                             Education§Masters     0.000000   0.000000
21                            Education§Masters      0.000000   0.000000
22                      Education§Masters degree     0.000000   0.000000
23             Job position§Asscoiate professor      0.000000   0.000000
24              Job position§Associate professor     0.000000   0.000000

                                  Feature
0                             Work tenure
1                  satisfied compensation
2              satisfaction with workload
3   mentally well and do not have anxiety
4           satisfied with job profession
5                          family support
6                               Education
7                                  Gender
8            good relationship with peers
9                      work is meaningful
10                              Education
11                            Work tenure
12                            Work tenure
13                                    age
14                                    age
15                                    age
16                                    age
17                           Job position
18                              Education
19                              Education
20                              Education
21                              Education
22                              Education
23                           Job position
24                           Job position

=== L1-Logistic (LASSO) — Grouped by Feature ===
                                  Feature  Importance  NonZero_Columns  \
0                             Work tenure    1.300798                1
1                  satisfied compensation    0.827426                1
2              satisfaction with workload    0.713693                1
3   mentally well and do not have anxiety    0.398365                1
4           satisfied with job profession    0.267116                1
5                          family support    0.248524                1
6                               Education    0.136890                1
7                                  Gender    0.116763                1
8            good relationship with peers    0.069503                1
9                      work is meaningful    0.061416                1
10                                    age    0.000000                0
11                           Job position    0.000000                0
12  satisfied with career and opportunity    0.000000                0
13                         monthly salary    0.000000                0
14       satisfied with work-life balance    0.000000                0
15                           working hour    0.000000                0

     Max_Abs  Columns
0   1.300798        3
1   0.827426        1
2   0.713693        1
3   0.398365        1
4   0.267116        1
5   0.248524        1
6   0.136890        7
7   0.116763        1
8   0.069503        1
9   0.061416        1
10  0.000000        4
11  0.000000       10
12  0.000000        1
13  0.000000        3
14  0.000000        1
15  0.000000        4

Class counts (TOI):
TOI (turnover intention)
0    325
1    201
Name: count, dtype: int64

In [10]:
import pandas as pd
import re
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegressionCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# --- Load dataset ---
df = pd.read_csv('/content/Final Primary_dataset_from_Indonesian_Private_University.csv')
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

# --- Features & target ---
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

df = df[features + [target]].dropna(subset=[target])
y = df[target].astype(int)

# --- Clean numeric features ---
def extract_number(s):
    if pd.isna(s): return np.nan
    s = str(s).replace(',', '')
    m = re.search(r'(-?\d+(?:\.\d+)?)', s)
    return float(m.group(1)) if m else np.nan

for col in ['age','Work tenure','working hour','monthly salary']:
    df[col] = df[col].apply(extract_number)

numeric_features = ['age','Work tenure','working hour','monthly salary']
categorical_features = [c for c in features if c not in numeric_features]

# --- Preprocessing ---
numeric_tf = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
categorical_tf = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', drop='first'))
])
preprocessor = ColumnTransformer([
    ('num', numeric_tf, numeric_features),
    ('cat', categorical_tf, categorical_features)
])

# --- Logistic Regression with L1 penalty (LASSO) ---
lasso = LogisticRegressionCV(
    Cs=10,
    penalty="l1",
    solver="liblinear",
    cv=5,
    class_weight="balanced",
    max_iter=2000,
    random_state=42
)

pipe = Pipeline([
    ('prep', preprocessor),
    ('clf', lasso)
])

# --- Fit ---
pipe.fit(df[features], y)

# --- Extract encoded feature names & coefficients ---
feature_names = pipe.named_steps['prep'].get_feature_names_out()
coefs = pipe.named_steps['clf'].coef_.ravel()

lasso_results = pd.DataFrame({
    'Encoded_Feature': feature_names,
    'Coefficient': coefs
})

# --- Map encoded → original feature ---
def to_original(name):
    # e.g. "cat__Job position_Manager" → "Job position"
    if "__" in name:
        after = name.split("__", 1)[1]   # drop "num__" or "cat__"
        return after.split("_", 1)[0]    # take only the feature name before first underscore
    return name

lasso_results['Original_Feature'] = lasso_results['Encoded_Feature'].apply(to_original)

# --- Group back to 16 original features ---
grouped = (
    lasso_results.groupby('Original_Feature', as_index=False)
    .agg(
        # max abs coefficient across dummies = feature strength
        MaxAbsCoef=('Coefficient', lambda x: np.max(np.abs(x))),
        Any_Selected=('Coefficient', lambda x: (x != 0).any()),
        Num_Encoded=('Encoded_Feature','count')
    )
    .sort_values('MaxAbsCoef', ascending=False)
    .reset_index(drop=True)
)

# Add a normalized score for easy comparison
grouped['Score_Norm'] = grouped['MaxAbsCoef'] / grouped['MaxAbsCoef'].max()

print("\n=== LASSO Logistic Regression Grouped by Original Feature ===")
print(grouped[['Original_Feature','MaxAbsCoef','Score_Norm','Any_Selected','Num_Encoded']])

=== LASSO Logistic Regression Grouped by Original Feature ===
                         Original_Feature  MaxAbsCoef  Score_Norm  \
0                  satisfied compensation    1.451340    1.000000
1   mentally well and do not have anxiety    1.423252    0.980647
2   satisfied with career and opportunity    0.651339    0.448785
3              satisfaction with workload    0.574261    0.395676
4                                     age    0.521691    0.359455
5                            working hour    0.507282    0.349527
6            good relationship with peers    0.433343    0.298581
7                               Education    0.378422    0.260740
8                          family support    0.346013    0.238409
9                                  Gender    0.272105    0.187485
10       satisfied with work-life balance    0.240439    0.165667
11                            Work tenure    0.207884    0.143236
12          satisfied with job profession    0.148626    0.102406
13                           Job position    0.089388    0.061590
14                         monthly salary    0.000607    0.000418
15                     work is meaningful    0.000000    0.000000

    Any_Selected  Num_Encoded
0           True            4
1           True            4
2           True            4
3           True            4
4           True            1
5           True            1
6           True            3
7           True            7
8           True            4
9           True            1
10          True            4
11          True            1
12          True            3
13          True           10
14          True            1
15         False            3

In [11]:
import pandas as pd
import re
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

# --- Load dataset ---
df = pd.read_csv('/content/Final Primary_dataset_from_Indonesian_Private_University.csv')
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

# --- Features & target ---
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

df = df[features + [target]].dropna(subset=[target])
y = df[target].astype(int)

# --- Clean numeric features ---
def extract_number(s):
    if pd.isna(s): return np.nan
    s = str(s).replace(',', '')
    m = re.search(r'(-?\d+(?:\.\d+)?)', s)
    return float(m.group(1)) if m else np.nan

for col in ['age','Work tenure','working hour','monthly salary']:
    df[col] = df[col].apply(extract_number)

numeric_features = ['age','Work tenure','working hour','monthly salary']
categorical_features = [c for c in features if c not in numeric_features]

# --- Preprocessing ---
numeric_tf = Pipeline([
    ('imputer', SimpleImputer(strategy='median'))
])
categorical_tf = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])
preprocessor = ColumnTransformer([
    ('num', numeric_tf, numeric_features),
    ('cat', categorical_tf, categorical_features)
])

# --- Random Forest pipeline ---
rf = Pipeline([
    ('prep', preprocessor),
    ('clf', RandomForestClassifier(n_estimators=200, random_state=42, class_weight='balanced'))
])

# --- Train/Test Split ---
X_train, X_test, y_train, y_test = train_test_split(df[features], y, test_size=0.3, random_state=42)

# --- Fit ---
rf.fit(X_train, y_train)

# --- Extract feature importances (dummy level) ---
model = rf.named_steps['clf']
encoded_names = rf.named_steps['prep'].get_feature_names_out()
importances = model.feature_importances_

importance_df = pd.DataFrame({
    'Encoded_Feature': encoded_names,
    'Importance': importances
})

# --- Map encoded → original feature ---
def to_original(name):
    # e.g. "cat__Job position_Manager" → "Job position"
    if "__" in name:
        after = name.split("__", 1)[1]
        return after.split("_", 1)[0]  # take only the feature name
    return name

importance_df['Original_Feature'] = importance_df['Encoded_Feature'].apply(to_original)

# --- Group back to original 16 features ---
grouped = (
    importance_df.groupby('Original_Feature', as_index=False)
    .agg(
        RF_Importance_Sum=('Importance','sum'),
        Num_Encoded=('Encoded_Feature','count')
    )
    .sort_values('RF_Importance_Sum', ascending=False)
    .reset_index(drop=True)
)

# Normalize importance
grouped['RF_Importance_Norm'] = grouped['RF_Importance_Sum'] / grouped['RF_Importance_Sum'].max()
grouped['Feature_Rank'] = range(1, len(grouped)+1)

print("\n=== Random Forest Feature Importance (Grouped by Original Feature) ===")
print(grouped[['Feature_Rank','Original_Feature','RF_Importance_Sum','RF_Importance_Norm','Num_Encoded']])

=== Random Forest Feature Importance (Grouped by Original Feature) ===
    Feature_Rank                       Original_Feature  RF_Importance_Sum  \
0              1             satisfaction with workload           0.134812
1              2       satisfied with work-life balance           0.118253
2              3  mentally well and do not have anxiety           0.080305
3              4                 satisfied compensation           0.071020
4              5                         family support           0.069639
5              6  satisfied with career and opportunity           0.069542
6              7                                    age           0.064331
7              8          satisfied with job profession           0.059236
8              9                           working hour           0.057913
9             10                           Job position           0.055500
10            11           good relationship with peers           0.049712
11            12                     work is meaningful           0.044125
12            13                            Work tenure           0.040823
13            14                              Education           0.039017
14            15                         monthly salary           0.024431
15            16                                 Gender           0.021339

    RF_Importance_Norm  Num_Encoded
0             1.000000            5
1             0.877165            5
2             0.595680            5
3             0.526807            5
4             0.516562            5
5             0.515842            5
6             0.477193            1
7             0.439399            4
8             0.429584            1
9             0.411685           10
10            0.368752            4
11            0.327306            4
12            0.302817            1
13            0.289418            8
14            0.181222            1
15            0.158283            2

In [12]:
import pandas as pd
import numpy as np
import re
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

# --- Load dataset ---
df = pd.read_csv('/content/Final Primary_dataset_from_Indonesian_Private_University.csv')
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

# --- Define features & target ---
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

df = df[features + [target]].dropna(subset=[target])
y = df[target].astype(int)

# --- Clean numeric columns ---
def extract_number(s):
    """Extract the first number from a string, else NaN."""
    if pd.isna(s):
        return np.nan
    s = str(s).replace(',', '')
    m = re.search(r'(-?\d+(?:\.\d+)?)', s)
    return float(m.group(1)) if m else np.nan

for col in ['age', 'Work tenure', 'working hour', 'monthly salary']:
    if col in df.columns:
        df[col] = df[col].apply(extract_number)

# --- Feature types ---
numeric_features = ['age', 'Work tenure', 'working hour', 'monthly salary']
categorical_features = [c for c in features if c not in numeric_features]

# --- Preprocessing ---
num_tf = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
cat_tf = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', drop='first'))
])

preprocessor = ColumnTransformer([
    ('num', num_tf, numeric_features),
    ('cat', cat_tf, categorical_features),
], remainder='drop', verbose_feature_names_out=True)

# --- Logistic Regression model ---
estimator = LogisticRegression(
    solver='liblinear',
    max_iter=2000,
    class_weight='balanced',
    random_state=42
)

# --- Wrap preprocessing + RFE ---
pipe = Pipeline([
    ('prep', preprocessor),
    ('rfe', RFE(estimator=estimator, n_features_to_select=8))
])

# --- Fit ---
pipe.fit(df[features], y)

# --- Get encoded feature names ---
encoded_names = pipe.named_steps['prep'].get_feature_names_out()

# --- Collect RFE results ---
rfe = pipe.named_steps['rfe']
rfe_results = pd.DataFrame({
    'Encoded_Feature': encoded_names,
    'Selected': rfe.support_,
    'Rank': rfe.ranking_
})

# --- Map back to original features ---
def to_original(name):
    after = name.split('__', 1)[1]   # drop "num__" or "cat__"
    return after.split('_', 1)[0]    # e.g. "Job position_Manager" → "Job position"

rfe_results['Original_Feature'] = rfe_results['Encoded_Feature'].apply(to_original)

# --- Aggregate per original feature ---
grouped = (
    rfe_results
    .groupby('Original_Feature', as_index=False)
    .agg(
        Best_Rank=('Rank', 'min'),
        Any_Selected=('Selected', 'max'),
        Columns=('Encoded_Feature', 'count')
    )
    .sort_values('Best_Rank', kind='mergesort')
    .reset_index(drop=True)
)

# Re-index 1..16 for clean ranking
grouped['Feature_Rank'] = range(1, len(grouped) + 1)

print("\n=== RFE Grouped by Original Feature ===")
print(grouped[['Feature_Rank','Original_Feature','Best_Rank','Any_Selected','Columns']])

=== RFE Grouped by Original Feature ===
    Feature_Rank                       Original_Feature  Best_Rank  \
0              1                              Education          1
1              2                         family support          1
2              3           good relationship with peers          1
3              4  mentally well and do not have anxiety          1
4              5                 satisfied compensation          1
5              6  satisfied with career and opportunity          1
6              7             satisfaction with workload          2
7              8       satisfied with work-life balance          4
8              9                           Job position          5
9             10                                    age          7
10            11          satisfied with job profession         14
11            12                                 Gender         15
12            13                           working hour         18
13            14                            Work tenure         23
14            15                     work is meaningful         27
15            16                         monthly salary         48

    Any_Selected  Columns
0           True        7
1           True        4
2           True        3
3           True        4
4           True        4
5           True        4
6          False        4
7          False        4
8          False       10
9          False        1
10         False        3
11         False        1
12         False        1
13         False        1
14         False        3
15         False        1

In [13]:
print(X.columns.tolist())

['age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour', 'satisfaction with workload', 'satisfied compensation', 'good relationship with peers', 'satisfied with career and opportunity', 'satisfied with job profession', 'monthly salary', 'satisfied with work-life balance', 'work is meaningful', 'family support', 'mentally well and do not have anxiety']

In [14]:
! pip install boruta

Collecting boruta
  Downloading Boruta-0.4.3-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.12/dist-packages (from boruta) (2.0.2)
Requirement already satisfied: scikit-learn>=0.17.1 in /usr/local/lib/python3.12/dist-packages (from boruta) (1.6.1)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.12/dist-packages (from boruta) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.17.1->boruta) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.17.1->boruta) (3.6.0)
Downloading Boruta-0.4.3-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.9/57.9 kB 1.3 MB/s eta 0:00:00
Installing collected packages: boruta
Successfully installed boruta-0.4.3

In [15]:
import pandas as pd
import numpy as np
import re
from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy
from sklearn.preprocessing import OneHotEncoder

# --- Load dataset ---
df = pd.read_csv('/content/Final Primary_dataset_from_Indonesian_Private_University.csv')
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

# --- Features & target ---
features = [
    'age', 'Gender', 'Work tenure', 'Education', 'Job position', 'working hour',
    'satisfaction with workload', 'satisfied compensation',
    'good relationship with peers', 'satisfied with career and opportunity',
    'satisfied with job profession', 'monthly salary',
    'satisfied with work-life balance', 'work is meaningful',
    'family support', 'mentally well and do not have anxiety'
]
target = 'TOI (turnover intention)'

df = df[features + [target]].dropna(subset=[target])
y = df[target].astype(int)

# --- Clean numeric columns ---
def extract_number(s):
    if pd.isna(s): return np.nan
    s = str(s).replace(',', '')
    m = re.search(r'(-?\d+(?:\.\d+)?)', s)
    return float(m.group(1)) if m else np.nan

for col in ['age','Work tenure','working hour','monthly salary']:
    df[col] = df[col].apply(extract_number)

# --- Split categorical vs numeric ---
cat_features = [c for c in features if c not in ['age','Work tenure','working hour','monthly salary']]
num_features = ['age','Work tenure','working hour','monthly salary']

# --- One-hot encode categorical ---
ohe = OneHotEncoder(handle_unknown='ignore', drop='first', sparse_output=False)
X_cat = ohe.fit_transform(df[cat_features])
cat_names = ohe.get_feature_names_out(cat_features)

# Combine numeric + categorical
X_num = df[num_features].to_numpy()
X = np.hstack([X_num, X_cat])
feature_names = num_features + list(cat_names)

# --- RandomForest model for Boruta ---
rf = RandomForestClassifier(
    n_estimators=100,
    n_jobs=-1,
    class_weight='balanced',
    random_state=42
)

# --- Run Boruta ---
feat_selector = BorutaPy(
    estimator=rf,
    n_estimators='auto',
    max_iter=20,
    verbose=2,
    random_state=42
)
feat_selector.fit(X, y.values)

# --- Collect Boruta results (encoded) ---
boruta_df = pd.DataFrame({
    'Feature_Encoded': feature_names,
    'Boruta_Support': feat_selector.support_,
    'Boruta_Ranking': feat_selector.ranking_
})

# --- Fit RF separately for importances ---
rf.fit(X, y)
importances = rf.feature_importances_

importance_df = pd.DataFrame({
    'Feature_Encoded': feature_names,
    'RF_Importance': importances
})

# --- Merge Boruta + RF ---
merged = boruta_df.merge(importance_df, on='Feature_Encoded', how='left')

# --- Map encoded → original feature ---
def to_original(name):
    # e.g. "Job position_Manager" → "Job position"
    return name.split('_', 1)[0] if '_' in name else name

merged['Original_Feature'] = merged['Feature_Encoded'].apply(to_original)

# --- Group back to original 16 features ---
grouped = (
    merged.groupby('Original_Feature', as_index=False)
    .agg(
        Boruta_Group_Support=('Boruta_Support', 'max'),
        Boruta_Best_Rank=('Boruta_Ranking', 'min'),
        RF_Importance_Sum=('RF_Importance', 'sum')
    )
)

# Normalize RF importance
grouped['RF_Importance_Norm'] = grouped['RF_Importance_Sum'] / grouped['RF_Importance_Sum'].max()

# Sort by Boruta rank, then importance
grouped = grouped.sort_values(['Boruta_Best_Rank','RF_Importance_Sum'],
                              ascending=[True,False]).reset_index(drop=True)

# Re-rank 1..16
grouped['Feature_Rank'] = range(1, len(grouped)+1)

print("\n=== Grouped Boruta + RF Feature Importance (16 features) ===")
print(grouped[['Feature_Rank','Original_Feature',
               'Boruta_Group_Support','Boruta_Best_Rank',
               'RF_Importance_Sum','RF_Importance_Norm']])

Iteration: 	1 / 20
Confirmed: 	0
Tentative: 	55
Rejected: 	0
Iteration: 	2 / 20
Confirmed: 	0
Tentative: 	55
Rejected: 	0
Iteration: 	3 / 20
Confirmed: 	0
Tentative: 	55
Rejected: 	0
Iteration: 	4 / 20
Confirmed: 	0
Tentative: 	55
Rejected: 	0
Iteration: 	5 / 20
Confirmed: 	0
Tentative: 	55
Rejected: 	0
Iteration: 	6 / 20
Confirmed: 	0
Tentative: 	55
Rejected: 	0
Iteration: 	7 / 20
Confirmed: 	0
Tentative: 	55
Rejected: 	0
Iteration: 	8 / 20
Confirmed: 	14
Tentative: 	6
Rejected: 	35
Iteration: 	9 / 20
Confirmed: 	14
Tentative: 	6
Rejected: 	35
Iteration: 	10 / 20
Confirmed: 	14
Tentative: 	6
Rejected: 	35
Iteration: 	11 / 20
Confirmed: 	14
Tentative: 	6
Rejected: 	35
Iteration: 	12 / 20
Confirmed: 	14
Tentative: 	6
Rejected: 	35
Iteration: 	13 / 20
Confirmed: 	14
Tentative: 	5
Rejected: 	36
Iteration: 	14 / 20
Confirmed: 	14
Tentative: 	5
Rejected: 	36
Iteration: 	15 / 20
Confirmed: 	14
Tentative: 	5
Rejected: 	36
Iteration: 	16 / 20
Confirmed: 	14
Tentative: 	4
Rejected: 	37
Iteration: 	17 / 20
Confirmed: 	14
Tentative: 	4
Rejected: 	37
Iteration: 	18 / 20
Confirmed: 	14
Tentative: 	4
Rejected: 	37
Iteration: 	19 / 20
Confirmed: 	14
Tentative: 	3
Rejected: 	38


BorutaPy finished running.

Iteration: 	20 / 20
Confirmed: 	14
Tentative: 	1
Rejected: 	40

=== Grouped Boruta + RF Feature Importance (16 features) ===
    Feature_Rank                       Original_Feature  Boruta_Group_Support  \
0              1             satisfaction with workload                  True
1              2       satisfied with work-life balance                  True
2              3                 satisfied compensation                  True
3              4                         family support                  True
4              5  satisfied with career and opportunity                  True
5              6  mentally well and do not have anxiety                  True
6              7                                    age                  True
7              8          satisfied with job profession                  True
8              9                           working hour                  True
9             10                            Work tenure                  True
10            11                         monthly salary                 False
11            12           good relationship with peers                 False
12            13                     work is meaningful                 False
13            14                              Education                 False
14            15                                 Gender                 False
15            16                           Job position                 False

    Boruta_Best_Rank  RF_Importance_Sum  RF_Importance_Norm
0                  1           0.153911            1.000000
1                  1           0.106455            0.691664
2                  1           0.084135            0.546647
3                  1           0.081913            0.532210
4                  1           0.081202            0.527589
5                  1           0.078301            0.508740
6                  1           0.060485            0.392989
7                  1           0.055826            0.362714
8                  1           0.041344            0.268625
9                  1           0.035196            0.228677
10                 2           0.032581            0.211685
11                 4           0.047657            0.309639
12                 6           0.033437            0.217251
13                 9           0.034531            0.224359
14                13           0.016713            0.108588
15                27           0.056315            0.365891